// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

/**
 * Protobuf type {@code process.PTY}
 */
@com.google.protobuf.Generated
public final class PTY extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:process.PTY)
    PTYOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "PTY");
  }
  // Use PTY.newBuilder() to construct.
  private PTY(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PTY() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProcessProto.internal_static_process_PTY_descriptor;
  }

  @Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return ProcessProto.internal_static_process_PTY_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProcessProto.internal_static_process_PTY_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PTY.class, Builder.class);
  }

  public interface SizeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.PTY.Size)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 cols = 1 [json_name = "cols"];</code>
     * @return The cols.
     */
    int getCols();

    /**
     * <code>uint32 rows = 2 [json_name = "rows"];</code>
     * @return The rows.
     */
    int getRows();
  }
  /**
   * Protobuf type {@code process.PTY.Size}
   */
  public static final class Size extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:process.PTY.Size)
      SizeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 0,
        /* suffix= */ "",
        "Size");
    }
    // Use Size.newBuilder() to construct.
    private Size(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Size() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessProto.internal_static_process_PTY_Size_descriptor;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return ProcessProto.internal_static_process_PTY_Size_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessProto.internal_static_process_PTY_Size_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Size.class, Builder.class);
    }

    public static final int COLS_FIELD_NUMBER = 1;
    private int cols_ = 0;
    /**
     * <code>uint32 cols = 1 [json_name = "cols"];</code>
     * @return The cols.
     */
    @Override
    public int getCols() {
      return cols_;
    }

    public static final int ROWS_FIELD_NUMBER = 2;
    private int rows_ = 0;
    /**
     * <code>uint32 rows = 2 [json_name = "rows"];</code>
     * @return The rows.
     */
    @Override
    public int getRows() {
      return rows_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cols_ != 0) {
        output.writeUInt32(1, cols_);
      }
      if (rows_ != 0) {
        output.writeUInt32(2, rows_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cols_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cols_);
      }
      if (rows_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rows_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Size)) {
        return super.equals(obj);
      }
      Size other = (Size) obj;

      if (getCols()
          != other.getCols()) return false;
      if (getRows()
          != other.getRows()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLS_FIELD_NUMBER;
      hash = (53 * hash) + getCols();
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRows();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Size parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Size parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Size parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Size parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Size parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Size parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Size parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Size parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Size parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Size parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Size parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Size parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Size prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.PTY.Size}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.PTY.Size)
        SizeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProcessProto.internal_static_process_PTY_Size_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProcessProto.internal_static_process_PTY_Size_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Size.class, Builder.class);
      }

      // Construct using io.openkruise.agents.client.e2b.envd.process.PTY.Size.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cols_ = 0;
        rows_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProcessProto.internal_static_process_PTY_Size_descriptor;
      }

      @Override
      public Size getDefaultInstanceForType() {
        return Size.getDefaultInstance();
      }

      @Override
      public Size build() {
        Size result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Size buildPartial() {
        Size result = new Size(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Size result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cols_ = cols_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rows_ = rows_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Size) {
          return mergeFrom((Size)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Size other) {
        if (other == Size.getDefaultInstance()) return this;
        if (other.getCols() != 0) {
          setCols(other.getCols());
        }
        if (other.getRows() != 0) {
          setRows(other.getRows());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cols_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                rows_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cols_ ;
      /**
       * <code>uint32 cols = 1 [json_name = "cols"];</code>
       * @return The cols.
       */
      @Override
      public int getCols() {
        return cols_;
      }
      /**
       * <code>uint32 cols = 1 [json_name = "cols"];</code>
       * @param value The cols to set.
       * @return This builder for chaining.
       */
      public Builder setCols(int value) {

        cols_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cols = 1 [json_name = "cols"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCols() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cols_ = 0;
        onChanged();
        return this;
      }

      private int rows_ ;
      /**
       * <code>uint32 rows = 2 [json_name = "rows"];</code>
       * @return The rows.
       */
      @Override
      public int getRows() {
        return rows_;
      }
      /**
       * <code>uint32 rows = 2 [json_name = "rows"];</code>
       * @param value The rows to set.
       * @return This builder for chaining.
       */
      public Builder setRows(int value) {

        rows_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rows = 2 [json_name = "rows"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRows() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rows_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:process.PTY.Size)
    }

    // @@protoc_insertion_point(class_scope:process.PTY.Size)
    private static final Size DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Size();
    }

    public static Size getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Size>
        PARSER = new com.google.protobuf.AbstractParser<Size>() {
      @Override
      public Size parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Size> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Size> getParserForType() {
      return PARSER;
    }

    @Override
    public Size getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int SIZE_FIELD_NUMBER = 1;
  private Size size_;
  /**
   * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
   * @return Whether the size field is set.
   */
  @Override
  public boolean hasSize() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
   * @return The size.
   */
  @Override
  public Size getSize() {
    return size_ == null ? Size.getDefaultInstance() : size_;
  }
  /**
   * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
   */
  @Override
  public SizeOrBuilder getSizeOrBuilder() {
    return size_ == null ? Size.getDefaultInstance() : size_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSize());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSize());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PTY)) {
      return super.equals(obj);
    }
    PTY other = (PTY) obj;

    if (hasSize() != other.hasSize()) return false;
    if (hasSize()) {
      if (!getSize()
          .equals(other.getSize())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PTY parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PTY parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PTY parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PTY parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PTY parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PTY parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PTY parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PTY parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PTY parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PTY parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PTY parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static PTY parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PTY prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.PTY}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.PTY)
      PTYOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessProto.internal_static_process_PTY_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessProto.internal_static_process_PTY_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PTY.class, Builder.class);
    }

    // Construct using io.openkruise.agents.client.e2b.envd.process.PTY.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSizeFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      size_ = null;
      if (sizeBuilder_ != null) {
        sizeBuilder_.dispose();
        sizeBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProcessProto.internal_static_process_PTY_descriptor;
    }

    @Override
    public PTY getDefaultInstanceForType() {
      return PTY.getDefaultInstance();
    }

    @Override
    public PTY build() {
      PTY result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PTY buildPartial() {
      PTY result = new PTY(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(PTY result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.size_ = sizeBuilder_ == null
            ? size_
            : sizeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PTY) {
        return mergeFrom((PTY)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PTY other) {
      if (other == PTY.getDefaultInstance()) return this;
      if (other.hasSize()) {
        mergeSize(other.getSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetSizeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Size size_;
    private com.google.protobuf.SingleFieldBuilder<
        Size, Size.Builder, SizeOrBuilder> sizeBuilder_;
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     * @return Whether the size field is set.
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     * @return The size.
     */
    public Size getSize() {
      if (sizeBuilder_ == null) {
        return size_ == null ? Size.getDefaultInstance() : size_;
      } else {
        return sizeBuilder_.getMessage();
      }
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    public Builder setSize(Size value) {
      if (sizeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        size_ = value;
      } else {
        sizeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    public Builder setSize(
        Size.Builder builderForValue) {
      if (sizeBuilder_ == null) {
        size_ = builderForValue.build();
      } else {
        sizeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    public Builder mergeSize(Size value) {
      if (sizeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          size_ != null &&
          size_ != Size.getDefaultInstance()) {
          getSizeBuilder().mergeFrom(value);
        } else {
          size_ = value;
        }
      } else {
        sizeBuilder_.mergeFrom(value);
      }
      if (size_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      size_ = null;
      if (sizeBuilder_ != null) {
        sizeBuilder_.dispose();
        sizeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    public Size.Builder getSizeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetSizeFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    public SizeOrBuilder getSizeOrBuilder() {
      if (sizeBuilder_ != null) {
        return sizeBuilder_.getMessageOrBuilder();
      } else {
        return size_ == null ?
            Size.getDefaultInstance() : size_;
      }
    }
    /**
     * <code>.process.PTY.Size size = 1 [json_name = "size"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        Size, Size.Builder, SizeOrBuilder>
        internalGetSizeFieldBuilder() {
      if (sizeBuilder_ == null) {
        sizeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            Size, Size.Builder, SizeOrBuilder>(
                getSize(),
                getParentForChildren(),
                isClean());
        size_ = null;
      }
      return sizeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:process.PTY)
  }

  // @@protoc_insertion_point(class_scope:process.PTY)
  private static final PTY DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PTY();
  }

  public static PTY getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PTY>
      PARSER = new com.google.protobuf.AbstractParser<PTY>() {
    @Override
    public PTY parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PTY> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PTY> getParserForType() {
    return PARSER;
  }

  @Override
  public PTY getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

