// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

@com.google.protobuf.Generated
public interface SendInputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.SendInputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  ProcessSelector getProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  ProcessSelectorOrBuilder getProcessOrBuilder();

  /**
   * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
   * @return Whether the input field is set.
   */
  boolean hasInput();
  /**
   * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
   * @return The input.
   */
  ProcessInput getInput();
  /**
   * <code>.process.ProcessInput input = 2 [json_name = "input"];</code>
   */
  ProcessInputOrBuilder getInputOrBuilder();
}
