// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

/**
 * Protobuf enum {@code process.Signal}
 */
@com.google.protobuf.Generated
public enum Signal
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SIGNAL_UNSPECIFIED = 0;</code>
   */
  SIGNAL_UNSPECIFIED(0),
  /**
   * <code>SIGNAL_SIGTERM = 15;</code>
   */
  SIGNAL_SIGTERM(15),
  /**
   * <code>SIGNAL_SIGKILL = 9;</code>
   */
  SIGNAL_SIGKILL(9),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "Signal");
  }
  /**
   * <code>SIGNAL_UNSPECIFIED = 0;</code>
   */
  public static final int SIGNAL_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SIGNAL_SIGTERM = 15;</code>
   */
  public static final int SIGNAL_SIGTERM_VALUE = 15;
  /**
   * <code>SIGNAL_SIGKILL = 9;</code>
   */
  public static final int SIGNAL_SIGKILL_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static Signal valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Signal forNumber(int value) {
    switch (value) {
      case 0: return SIGNAL_UNSPECIFIED;
      case 15: return SIGNAL_SIGTERM;
      case 9: return SIGNAL_SIGKILL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Signal>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Signal> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Signal>() {
          public Signal findValueByNumber(int number) {
            return Signal.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ProcessProto.getDescriptor().getEnumType(0);
  }

  private static final Signal[] VALUES = values();

  public static Signal valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Signal(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:process.Signal)
}

