// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

@com.google.protobuf.Generated
public interface StreamInputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.StreamInputRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
   * @return The start.
   */
  StreamInputRequest.StartEvent getStart();
  /**
   * <code>.process.StreamInputRequest.StartEvent start = 1 [json_name = "start"];</code>
   */
  StreamInputRequest.StartEventOrBuilder getStartOrBuilder();

  /**
   * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
   * @return The data.
   */
  StreamInputRequest.DataEvent getData();
  /**
   * <code>.process.StreamInputRequest.DataEvent data = 2 [json_name = "data"];</code>
   */
  StreamInputRequest.DataEventOrBuilder getDataOrBuilder();

  /**
   * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   * @return Whether the keepalive field is set.
   */
  boolean hasKeepalive();
  /**
   * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   * @return The keepalive.
   */
  StreamInputRequest.KeepAlive getKeepalive();
  /**
   * <code>.process.StreamInputRequest.KeepAlive keepalive = 3 [json_name = "keepalive"];</code>
   */
  StreamInputRequest.KeepAliveOrBuilder getKeepaliveOrBuilder();

  StreamInputRequest.EventCase getEventCase();
}
