// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

@com.google.protobuf.Generated
public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:process.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  boolean hasProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  ProcessSelector getProcess();
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  ProcessSelectorOrBuilder getProcessOrBuilder();

  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return Whether the pty field is set.
   */
  boolean hasPty();
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   * @return The pty.
   */
  PTY getPty();
  /**
   * <code>optional .process.PTY pty = 2 [json_name = "pty"];</code>
   */
  PTYOrBuilder getPtyOrBuilder();
}
