// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

/**
 * Protobuf type {@code process.CloseStdinRequest}
 */
@com.google.protobuf.Generated
public final class CloseStdinRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:process.CloseStdinRequest)
    CloseStdinRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "CloseStdinRequest");
  }
  // Use CloseStdinRequest.newBuilder() to construct.
  private CloseStdinRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CloseStdinRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProcessProto.internal_static_process_CloseStdinRequest_descriptor;
  }

  @Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return ProcessProto.internal_static_process_CloseStdinRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProcessProto.internal_static_process_CloseStdinRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CloseStdinRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int PROCESS_FIELD_NUMBER = 1;
  private ProcessSelector process_;
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return Whether the process field is set.
   */
  @Override
  public boolean hasProcess() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   * @return The process.
   */
  @Override
  public ProcessSelector getProcess() {
    return process_ == null ? ProcessSelector.getDefaultInstance() : process_;
  }
  /**
   * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
   */
  @Override
  public ProcessSelectorOrBuilder getProcessOrBuilder() {
    return process_ == null ? ProcessSelector.getDefaultInstance() : process_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getProcess());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProcess());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CloseStdinRequest)) {
      return super.equals(obj);
    }
    CloseStdinRequest other = (CloseStdinRequest) obj;

    if (hasProcess() != other.hasProcess()) return false;
    if (hasProcess()) {
      if (!getProcess()
          .equals(other.getProcess())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProcess()) {
      hash = (37 * hash) + PROCESS_FIELD_NUMBER;
      hash = (53 * hash) + getProcess().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CloseStdinRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CloseStdinRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CloseStdinRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CloseStdinRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CloseStdinRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CloseStdinRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CloseStdinRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CloseStdinRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CloseStdinRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CloseStdinRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CloseStdinRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static CloseStdinRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CloseStdinRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.CloseStdinRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.CloseStdinRequest)
      CloseStdinRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessProto.internal_static_process_CloseStdinRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessProto.internal_static_process_CloseStdinRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CloseStdinRequest.class, Builder.class);
    }

    // Construct using io.openkruise.agents.client.e2b.envd.process.CloseStdinRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetProcessFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProcessProto.internal_static_process_CloseStdinRequest_descriptor;
    }

    @Override
    public CloseStdinRequest getDefaultInstanceForType() {
      return CloseStdinRequest.getDefaultInstance();
    }

    @Override
    public CloseStdinRequest build() {
      CloseStdinRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CloseStdinRequest buildPartial() {
      CloseStdinRequest result = new CloseStdinRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CloseStdinRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.process_ = processBuilder_ == null
            ? process_
            : processBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CloseStdinRequest) {
        return mergeFrom((CloseStdinRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CloseStdinRequest other) {
      if (other == CloseStdinRequest.getDefaultInstance()) return this;
      if (other.hasProcess()) {
        mergeProcess(other.getProcess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetProcessFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ProcessSelector process_;
    private com.google.protobuf.SingleFieldBuilder<
        ProcessSelector, ProcessSelector.Builder, ProcessSelectorOrBuilder> processBuilder_;
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return Whether the process field is set.
     */
    public boolean hasProcess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     * @return The process.
     */
    public ProcessSelector getProcess() {
      if (processBuilder_ == null) {
        return process_ == null ? ProcessSelector.getDefaultInstance() : process_;
      } else {
        return processBuilder_.getMessage();
      }
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder setProcess(ProcessSelector value) {
      if (processBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        process_ = value;
      } else {
        processBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder setProcess(
        ProcessSelector.Builder builderForValue) {
      if (processBuilder_ == null) {
        process_ = builderForValue.build();
      } else {
        processBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder mergeProcess(ProcessSelector value) {
      if (processBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          process_ != null &&
          process_ != ProcessSelector.getDefaultInstance()) {
          getProcessBuilder().mergeFrom(value);
        } else {
          process_ = value;
        }
      } else {
        processBuilder_.mergeFrom(value);
      }
      if (process_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public Builder clearProcess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      process_ = null;
      if (processBuilder_ != null) {
        processBuilder_.dispose();
        processBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public ProcessSelector.Builder getProcessBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetProcessFieldBuilder().getBuilder();
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    public ProcessSelectorOrBuilder getProcessOrBuilder() {
      if (processBuilder_ != null) {
        return processBuilder_.getMessageOrBuilder();
      } else {
        return process_ == null ?
            ProcessSelector.getDefaultInstance() : process_;
      }
    }
    /**
     * <code>.process.ProcessSelector process = 1 [json_name = "process"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ProcessSelector, ProcessSelector.Builder, ProcessSelectorOrBuilder>
        internalGetProcessFieldBuilder() {
      if (processBuilder_ == null) {
        processBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ProcessSelector, ProcessSelector.Builder, ProcessSelectorOrBuilder>(
                getProcess(),
                getParentForChildren(),
                isClean());
        process_ = null;
      }
      return processBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:process.CloseStdinRequest)
  }

  // @@protoc_insertion_point(class_scope:process.CloseStdinRequest)
  private static final CloseStdinRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CloseStdinRequest();
  }

  public static CloseStdinRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CloseStdinRequest>
      PARSER = new com.google.protobuf.AbstractParser<CloseStdinRequest>() {
    @Override
    public CloseStdinRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CloseStdinRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CloseStdinRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CloseStdinRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

