// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/process.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.process;

/**
 * Protobuf type {@code process.ProcessSelector}
 */
@com.google.protobuf.Generated
public final class ProcessSelector extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:process.ProcessSelector)
    ProcessSelectorOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "ProcessSelector");
  }
  // Use ProcessSelector.newBuilder() to construct.
  private ProcessSelector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProcessSelector() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProcessProto.internal_static_process_ProcessSelector_descriptor;
  }

  @Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return ProcessProto.internal_static_process_ProcessSelector_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProcessProto.internal_static_process_ProcessSelector_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProcessSelector.class, Builder.class);
  }

  private int selectorCase_ = 0;
  @SuppressWarnings("serial")
  private Object selector_;
  public enum SelectorCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    PID(1),
    TAG(2),
    SELECTOR_NOT_SET(0);
    private final int value;
    private SelectorCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SelectorCase valueOf(int value) {
      return forNumber(value);
    }

    public static SelectorCase forNumber(int value) {
      switch (value) {
        case 1: return PID;
        case 2: return TAG;
        case 0: return SELECTOR_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SelectorCase
  getSelectorCase() {
    return SelectorCase.forNumber(
        selectorCase_);
  }

  public static final int PID_FIELD_NUMBER = 1;
  /**
   * <code>uint32 pid = 1 [json_name = "pid"];</code>
   * @return Whether the pid field is set.
   */
  @Override
  public boolean hasPid() {
    return selectorCase_ == 1;
  }
  /**
   * <code>uint32 pid = 1 [json_name = "pid"];</code>
   * @return The pid.
   */
  @Override
  public int getPid() {
    if (selectorCase_ == 1) {
      return (Integer) selector_;
    }
    return 0;
  }

  public static final int TAG_FIELD_NUMBER = 2;
  /**
   * <code>string tag = 2 [json_name = "tag"];</code>
   * @return Whether the tag field is set.
   */
  public boolean hasTag() {
    return selectorCase_ == 2;
  }
  /**
   * <code>string tag = 2 [json_name = "tag"];</code>
   * @return The tag.
   */
  public String getTag() {
    if (selectorCase_ != 2) {
      return "";
    }
    Object ref = selector_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      selector_ = s;
      return s;
    }
  }
  /**
   * <code>string tag = 2 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  public com.google.protobuf.ByteString
      getTagBytes() {
    if (selectorCase_ != 2) {
      return com.google.protobuf.ByteString.copyFromUtf8("");
    }
    Object ref = selector_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      selector_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (selectorCase_ == 1) {
      output.writeUInt32(
          1, (int)((Integer) selector_));
    }
    if (selectorCase_ == 2) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, selector_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (selectorCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(
            1, (int)((Integer) selector_));
    }
    if (selectorCase_ == 2) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, selector_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProcessSelector)) {
      return super.equals(obj);
    }
    ProcessSelector other = (ProcessSelector) obj;

    if (!getSelectorCase().equals(other.getSelectorCase())) return false;
    switch (selectorCase_) {
      case 1:
        if (getPid()
            != other.getPid()) return false;
        break;
      case 2:
        if (!getTag()
            .equals(other.getTag())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (selectorCase_) {
      case 1:
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + getPid();
        break;
      case 2:
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTag().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ProcessSelector parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProcessSelector parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProcessSelector parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProcessSelector parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProcessSelector parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProcessSelector parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProcessSelector parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ProcessSelector parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ProcessSelector parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ProcessSelector parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProcessSelector parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ProcessSelector parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ProcessSelector prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code process.ProcessSelector}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:process.ProcessSelector)
      ProcessSelectorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProcessProto.internal_static_process_ProcessSelector_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProcessProto.internal_static_process_ProcessSelector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProcessSelector.class, Builder.class);
    }

    // Construct using io.openkruise.agents.client.e2b.envd.process.ProcessSelector.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      selectorCase_ = 0;
      selector_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProcessProto.internal_static_process_ProcessSelector_descriptor;
    }

    @Override
    public ProcessSelector getDefaultInstanceForType() {
      return ProcessSelector.getDefaultInstance();
    }

    @Override
    public ProcessSelector build() {
      ProcessSelector result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ProcessSelector buildPartial() {
      ProcessSelector result = new ProcessSelector(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(ProcessSelector result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(ProcessSelector result) {
      result.selectorCase_ = selectorCase_;
      result.selector_ = this.selector_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProcessSelector) {
        return mergeFrom((ProcessSelector)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProcessSelector other) {
      if (other == ProcessSelector.getDefaultInstance()) return this;
      switch (other.getSelectorCase()) {
        case PID: {
          setPid(other.getPid());
          break;
        }
        case TAG: {
          selectorCase_ = 2;
          selector_ = other.selector_;
          onChanged();
          break;
        }
        case SELECTOR_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              selector_ = input.readUInt32();
              selectorCase_ = 1;
              break;
            } // case 8
            case 18: {
              selectorCase_ = 2;
              selector_ = input.readStringRequireUtf8();
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int selectorCase_ = 0;
    private Object selector_;
    public SelectorCase
        getSelectorCase() {
      return SelectorCase.forNumber(
          selectorCase_);
    }

    public Builder clearSelector() {
      selectorCase_ = 0;
      selector_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>uint32 pid = 1 [json_name = "pid"];</code>
     * @return Whether the pid field is set.
     */
    public boolean hasPid() {
      return selectorCase_ == 1;
    }
    /**
     * <code>uint32 pid = 1 [json_name = "pid"];</code>
     * @return The pid.
     */
    public int getPid() {
      if (selectorCase_ == 1) {
        return (Integer) selector_;
      }
      return 0;
    }
    /**
     * <code>uint32 pid = 1 [json_name = "pid"];</code>
     * @param value The pid to set.
     * @return This builder for chaining.
     */
    public Builder setPid(int value) {

      selectorCase_ = 1;
      selector_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 pid = 1 [json_name = "pid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPid() {
      if (selectorCase_ == 1) {
        selectorCase_ = 0;
        selector_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string tag = 2 [json_name = "tag"];</code>
     * @return Whether the tag field is set.
     */
    @Override
    public boolean hasTag() {
      return selectorCase_ == 2;
    }
    /**
     * <code>string tag = 2 [json_name = "tag"];</code>
     * @return The tag.
     */
    @Override
    public String getTag() {
      if (selectorCase_ != 2) {
        return "";
      }
      Object ref = selector_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
          selector_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tag = 2 [json_name = "tag"];</code>
     * @return The bytes for tag.
     */
    @Override
    public com.google.protobuf.ByteString
        getTagBytes() {
      if (selectorCase_ != 2) {
        return com.google.protobuf.ByteString.copyFromUtf8(        "");
      }
      Object ref = selector_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        selector_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tag = 2 [json_name = "tag"];</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      selectorCase_ = 2;
      selector_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tag = 2 [json_name = "tag"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      if (selectorCase_ == 2) {
        selectorCase_ = 0;
        selector_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string tag = 2 [json_name = "tag"];</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      selectorCase_ = 2;
      selector_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:process.ProcessSelector)
  }

  // @@protoc_insertion_point(class_scope:process.ProcessSelector)
  private static final ProcessSelector DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProcessSelector();
  }

  public static ProcessSelector getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProcessSelector>
      PARSER = new com.google.protobuf.AbstractParser<ProcessSelector>() {
    @Override
    public ProcessSelector parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProcessSelector> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ProcessSelector> getParserForType() {
    return PARSER;
  }

  @Override
  public ProcessSelector getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

