/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1PersistentVolumeClaimList;
import io.kubernetes.client.openapi.models.V1PodTemplateSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * spec defines the desired state of Sandbox
 */
@ApiModel(description = "spec defines the desired state of Sandbox")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2026-04-03T09:31:05.089Z[Etc/UTC]")
public class V1alpha1SandboxSpec {
    public static final String SERIALIZED_NAME_PAUSE_TIME = "pauseTime";
    @SerializedName(SERIALIZED_NAME_PAUSE_TIME)
    private OffsetDateTime pauseTime;

    public static final String SERIALIZED_NAME_PAUSED = "paused";
    @SerializedName(SERIALIZED_NAME_PAUSED)
    private Boolean paused;

    public static final String SERIALIZED_NAME_PERSISTENT_CONTENTS = "persistentContents";
    @SerializedName(SERIALIZED_NAME_PERSISTENT_CONTENTS)
    private List<String> persistentContents = null;

    public static final String SERIALIZED_NAME_RUNTIMES = "runtimes";
    @SerializedName(SERIALIZED_NAME_RUNTIMES)
    private List<V1alpha1Runtimes> runtimes = null;

    public static final String SERIALIZED_NAME_SHUTDOWN_TIME = "shutdownTime";
    @SerializedName(SERIALIZED_NAME_SHUTDOWN_TIME)
    private OffsetDateTime shutdownTime;

    public static final String SERIALIZED_NAME_TEMPLATE = "template";
    @SerializedName(SERIALIZED_NAME_TEMPLATE)
    private V1PodTemplateSpec template;

    public static final String SERIALIZED_NAME_TEMPLATE_REF = "templateRef";
    @SerializedName(SERIALIZED_NAME_TEMPLATE_REF)
    private V1alpha1SandboxSetSpecTemplateRef templateRef;

    public static final String SERIALIZED_NAME_VOLUME_CLAIM_TEMPLATES = "volumeClaimTemplates";
    @SerializedName(SERIALIZED_NAME_VOLUME_CLAIM_TEMPLATES)
    private V1PersistentVolumeClaimList volumeClaimTemplates;

    public V1alpha1SandboxSpec pauseTime(OffsetDateTime pauseTime) {

        this.pauseTime = pauseTime;
        return this;
    }

    /**
     * PauseTime - Absolute time when the sandbox will be paused automatically.
     *
     * @return pauseTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "PauseTime - Absolute time when the sandbox will be paused automatically.")

    public OffsetDateTime getPauseTime() {
        return pauseTime;
    }

    public void setPauseTime(OffsetDateTime pauseTime) {
        this.pauseTime = pauseTime;
    }

    public V1alpha1SandboxSpec paused(Boolean paused) {

        this.paused = paused;
        return this;
    }

    /**
     * Paused indicates whether pause the sandbox pod.
     *
     * @return paused
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Paused indicates whether pause the sandbox pod.")

    public Boolean getPaused() {
        return paused;
    }

    public void setPaused(Boolean paused) {
        this.paused = paused;
    }

    public V1alpha1SandboxSpec persistentContents(List<String> persistentContents) {

        this.persistentContents = persistentContents;
        return this;
    }

    public V1alpha1SandboxSpec addPersistentContentsItem(String persistentContentsItem) {
        if (this.persistentContents == null) {
            this.persistentContents = new ArrayList<>();
        }
        this.persistentContents.add(persistentContentsItem);
        return this;
    }

    /**
     * PersistentContents indicates resume pod with persistent content, Enum: ip, memory, filesystem
     *
     * @return persistentContents
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "PersistentContents indicates resume pod with persistent content, Enum: ip, memory, filesystem")

    public List<String> getPersistentContents() {
        return persistentContents;
    }

    public void setPersistentContents(List<String> persistentContents) {
        this.persistentContents = persistentContents;
    }

    public V1alpha1SandboxSpec runtimes(List<V1alpha1Runtimes> runtimes) {

        this.runtimes = runtimes;
        return this;
    }

    public V1alpha1SandboxSpec addRuntimesItem(V1alpha1Runtimes runtimesItem) {
        if (this.runtimes == null) {
            this.runtimes = new ArrayList<>();
        }
        this.runtimes.add(runtimesItem);
        return this;
    }

    /**
     * Runtimes - Runtime configuration for sandbox object
     *
     * @return runtimes
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Runtimes - Runtime configuration for sandbox object")

    public List<V1alpha1Runtimes> getRuntimes() {
        return runtimes;
    }

    public void setRuntimes(List<V1alpha1Runtimes> runtimes) {
        this.runtimes = runtimes;
    }

    public V1alpha1SandboxSpec shutdownTime(OffsetDateTime shutdownTime) {

        this.shutdownTime = shutdownTime;
        return this;
    }

    /**
     * ShutdownTime - Absolute time when the sandbox is deleted. If a time in the past is provided, the sandbox will be
     * deleted immediately.
     *
     * @return shutdownTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "ShutdownTime - Absolute time when the sandbox is deleted. If a time in the past is provided, the "
            + "sandbox will be deleted immediately.")

    public OffsetDateTime getShutdownTime() {
        return shutdownTime;
    }

    public void setShutdownTime(OffsetDateTime shutdownTime) {
        this.shutdownTime = shutdownTime;
    }

    public V1alpha1SandboxSpec template(V1PodTemplateSpec template) {

        this.template = template;
        return this;
    }

    /**
     * Template describes the pods that will be created. Template is mutual exclusive with TemplateRef
     *
     * @return template
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(
        value = "Template describes the pods that will be created. Template is mutual exclusive with TemplateRef")

    public V1PodTemplateSpec getTemplate() {
        return template;
    }

    public void setTemplate(V1PodTemplateSpec template) {
        this.template = template;
    }

    public V1alpha1SandboxSpec templateRef(V1alpha1SandboxSetSpecTemplateRef templateRef) {

        this.templateRef = templateRef;
        return this;
    }

    /**
     * Get templateRef
     *
     * @return templateRef
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1alpha1SandboxSetSpecTemplateRef getTemplateRef() {
        return templateRef;
    }

    public void setTemplateRef(V1alpha1SandboxSetSpecTemplateRef templateRef) {
        this.templateRef = templateRef;
    }

    public V1alpha1SandboxSpec volumeClaimTemplates(V1PersistentVolumeClaimList volumeClaimTemplates) {

        this.volumeClaimTemplates = volumeClaimTemplates;
        return this;
    }

    /**
     * VolumeClaimTemplates is a list of PVC templates to create for this Sandbox.
     *
     * @return volumeClaimTemplates
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "VolumeClaimTemplates is a list of PVC templates to create for this Sandbox.")

    public V1PersistentVolumeClaimList getVolumeClaimTemplates() {
        return volumeClaimTemplates;
    }

    public void setVolumeClaimTemplates(V1PersistentVolumeClaimList volumeClaimTemplates) {
        this.volumeClaimTemplates = volumeClaimTemplates;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1alpha1SandboxSpec v1alpha1SandboxSpec = (V1alpha1SandboxSpec)o;
        return Objects.equals(this.pauseTime, v1alpha1SandboxSpec.pauseTime) &&
            Objects.equals(this.paused, v1alpha1SandboxSpec.paused) &&
            Objects.equals(this.persistentContents, v1alpha1SandboxSpec.persistentContents) &&
            Objects.equals(this.runtimes, v1alpha1SandboxSpec.runtimes) &&
            Objects.equals(this.shutdownTime, v1alpha1SandboxSpec.shutdownTime) &&
            Objects.equals(this.template, v1alpha1SandboxSpec.template) &&
            Objects.equals(this.templateRef, v1alpha1SandboxSpec.templateRef) &&
            Objects.equals(this.volumeClaimTemplates, v1alpha1SandboxSpec.volumeClaimTemplates);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pauseTime, paused, persistentContents, runtimes, shutdownTime, template, templateRef,
            volumeClaimTemplates);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1alpha1SandboxSpec {\n");
        sb.append("    pauseTime: ").append(toIndentedString(pauseTime)).append("\n");
        sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
        sb.append("    persistentContents: ").append(toIndentedString(persistentContents)).append("\n");
        sb.append("    runtimes: ").append(toIndentedString(runtimes)).append("\n");
        sb.append("    shutdownTime: ").append(toIndentedString(shutdownTime)).append("\n");
        sb.append("    template: ").append(toIndentedString(template)).append("\n");
        sb.append("    templateRef: ").append(toIndentedString(templateRef)).append("\n");
        sb.append("    volumeClaimTemplates: ").append(toIndentedString(volumeClaimTemplates)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

