/*
 * E2B API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.e2b.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.openkruise.agents.client.e2b.api.invoker.JSON;

/**
 * IdentifierMaskingDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T15:28:00.691+08:00[Asia/Shanghai]")
public class IdentifierMaskingDetails {
  public static final String SERIALIZED_NAME_PREFIX = "prefix";
  @SerializedName(SERIALIZED_NAME_PREFIX)
  private String prefix;

  public static final String SERIALIZED_NAME_VALUE_LENGTH = "valueLength";
  @SerializedName(SERIALIZED_NAME_VALUE_LENGTH)
  private Integer valueLength;

  public static final String SERIALIZED_NAME_MASKED_VALUE_PREFIX = "maskedValuePrefix";
  @SerializedName(SERIALIZED_NAME_MASKED_VALUE_PREFIX)
  private String maskedValuePrefix;

  public static final String SERIALIZED_NAME_MASKED_VALUE_SUFFIX = "maskedValueSuffix";
  @SerializedName(SERIALIZED_NAME_MASKED_VALUE_SUFFIX)
  private String maskedValueSuffix;

  public IdentifierMaskingDetails() {
  }

  public IdentifierMaskingDetails prefix(String prefix) {
    
    this.prefix = prefix;
    return this;
  }

   /**
   * Prefix that identifies the token or key type
   * @return prefix
  **/
  @javax.annotation.Nonnull
  public String getPrefix() {
    return prefix;
  }


  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  public IdentifierMaskingDetails valueLength(Integer valueLength) {
    
    this.valueLength = valueLength;
    return this;
  }

   /**
   * Length of the token or key
   * @return valueLength
  **/
  @javax.annotation.Nonnull
  public Integer getValueLength() {
    return valueLength;
  }


  public void setValueLength(Integer valueLength) {
    this.valueLength = valueLength;
  }


  public IdentifierMaskingDetails maskedValuePrefix(String maskedValuePrefix) {
    
    this.maskedValuePrefix = maskedValuePrefix;
    return this;
  }

   /**
   * Prefix used in masked version of the token or key
   * @return maskedValuePrefix
  **/
  @javax.annotation.Nonnull
  public String getMaskedValuePrefix() {
    return maskedValuePrefix;
  }


  public void setMaskedValuePrefix(String maskedValuePrefix) {
    this.maskedValuePrefix = maskedValuePrefix;
  }


  public IdentifierMaskingDetails maskedValueSuffix(String maskedValueSuffix) {
    
    this.maskedValueSuffix = maskedValueSuffix;
    return this;
  }

   /**
   * Suffix used in masked version of the token or key
   * @return maskedValueSuffix
  **/
  @javax.annotation.Nonnull
  public String getMaskedValueSuffix() {
    return maskedValueSuffix;
  }


  public void setMaskedValueSuffix(String maskedValueSuffix) {
    this.maskedValueSuffix = maskedValueSuffix;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the IdentifierMaskingDetails instance itself
   */
  public IdentifierMaskingDetails putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentifierMaskingDetails identifierMaskingDetails = (IdentifierMaskingDetails) o;
    return Objects.equals(this.prefix, identifierMaskingDetails.prefix) &&
        Objects.equals(this.valueLength, identifierMaskingDetails.valueLength) &&
        Objects.equals(this.maskedValuePrefix, identifierMaskingDetails.maskedValuePrefix) &&
        Objects.equals(this.maskedValueSuffix, identifierMaskingDetails.maskedValueSuffix)&&
        Objects.equals(this.additionalProperties, identifierMaskingDetails.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefix, valueLength, maskedValuePrefix, maskedValueSuffix, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentifierMaskingDetails {\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    valueLength: ").append(toIndentedString(valueLength)).append("\n");
    sb.append("    maskedValuePrefix: ").append(toIndentedString(maskedValuePrefix)).append("\n");
    sb.append("    maskedValueSuffix: ").append(toIndentedString(maskedValueSuffix)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("prefix");
    openapiFields.add("valueLength");
    openapiFields.add("maskedValuePrefix");
    openapiFields.add("maskedValueSuffix");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("prefix");
    openapiRequiredFields.add("valueLength");
    openapiRequiredFields.add("maskedValuePrefix");
    openapiRequiredFields.add("maskedValueSuffix");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to IdentifierMaskingDetails
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!IdentifierMaskingDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IdentifierMaskingDetails is not found in the empty JSON string", IdentifierMaskingDetails.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IdentifierMaskingDetails.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prefix").toString()));
      }
      if (!jsonObj.get("maskedValuePrefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maskedValuePrefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maskedValuePrefix").toString()));
      }
      if (!jsonObj.get("maskedValueSuffix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `maskedValueSuffix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("maskedValueSuffix").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IdentifierMaskingDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IdentifierMaskingDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IdentifierMaskingDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IdentifierMaskingDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<IdentifierMaskingDetails>() {
           @Override
           public void write(JsonWriter out, IdentifierMaskingDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public IdentifierMaskingDetails read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             IdentifierMaskingDetails instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IdentifierMaskingDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IdentifierMaskingDetails
  * @throws IOException if the JSON string is invalid with respect to IdentifierMaskingDetails
  */
  public static IdentifierMaskingDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IdentifierMaskingDetails.class);
  }

 /**
  * Convert an instance of IdentifierMaskingDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

