/*
 * E2B API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.e2b.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.agents.client.e2b.api.models.SandboxLifecycle;
import io.openkruise.agents.client.e2b.api.models.SandboxNetworkConfig;
import io.openkruise.agents.client.e2b.api.models.SandboxState;
import io.openkruise.agents.client.e2b.api.models.SandboxVolumeMount;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.openkruise.agents.client.e2b.api.invoker.JSON;

/**
 * SandboxDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T15:28:00.691+08:00[Asia/Shanghai]")
public class SandboxDetail {
  public static final String SERIALIZED_NAME_TEMPLATE_I_D = "templateID";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_I_D)
  private String templateID;

  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  private String alias;

  public static final String SERIALIZED_NAME_SANDBOX_I_D = "sandboxID";
  @SerializedName(SERIALIZED_NAME_SANDBOX_I_D)
  private String sandboxID;

  public static final String SERIALIZED_NAME_CLIENT_I_D = "clientID";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_CLIENT_I_D)
  private String clientID;

  public static final String SERIALIZED_NAME_STARTED_AT = "startedAt";
  @SerializedName(SERIALIZED_NAME_STARTED_AT)
  private OffsetDateTime startedAt;

  public static final String SERIALIZED_NAME_END_AT = "endAt";
  @SerializedName(SERIALIZED_NAME_END_AT)
  private OffsetDateTime endAt;

  public static final String SERIALIZED_NAME_ENVD_VERSION = "envdVersion";
  @SerializedName(SERIALIZED_NAME_ENVD_VERSION)
  private String envdVersion;

  public static final String SERIALIZED_NAME_ENVD_ACCESS_TOKEN = "envdAccessToken";
  @SerializedName(SERIALIZED_NAME_ENVD_ACCESS_TOKEN)
  private String envdAccessToken;

  public static final String SERIALIZED_NAME_ALLOW_INTERNET_ACCESS = "allowInternetAccess";
  @SerializedName(SERIALIZED_NAME_ALLOW_INTERNET_ACCESS)
  private Boolean allowInternetAccess;

  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  private String domain;

  public static final String SERIALIZED_NAME_CPU_COUNT = "cpuCount";
  @SerializedName(SERIALIZED_NAME_CPU_COUNT)
  private Integer cpuCount;

  public static final String SERIALIZED_NAME_MEMORY_M_B = "memoryMB";
  @SerializedName(SERIALIZED_NAME_MEMORY_M_B)
  private Integer memoryMB;

  public static final String SERIALIZED_NAME_DISK_SIZE_M_B = "diskSizeMB";
  @SerializedName(SERIALIZED_NAME_DISK_SIZE_M_B)
  private Integer diskSizeMB;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private SandboxState state;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  private SandboxNetworkConfig network;

  public static final String SERIALIZED_NAME_LIFECYCLE = "lifecycle";
  @SerializedName(SERIALIZED_NAME_LIFECYCLE)
  private SandboxLifecycle lifecycle;

  public static final String SERIALIZED_NAME_VOLUME_MOUNTS = "volumeMounts";
  @SerializedName(SERIALIZED_NAME_VOLUME_MOUNTS)
  private List<SandboxVolumeMount> volumeMounts;

  public SandboxDetail() {
  }

  public SandboxDetail templateID(String templateID) {
    
    this.templateID = templateID;
    return this;
  }

   /**
   * Identifier of the template from which is the sandbox created
   * @return templateID
  **/
  @javax.annotation.Nonnull
  public String getTemplateID() {
    return templateID;
  }


  public void setTemplateID(String templateID) {
    this.templateID = templateID;
  }


  public SandboxDetail alias(String alias) {
    
    this.alias = alias;
    return this;
  }

   /**
   * Alias of the template
   * @return alias
  **/
  @javax.annotation.Nullable
  public String getAlias() {
    return alias;
  }


  public void setAlias(String alias) {
    this.alias = alias;
  }


  public SandboxDetail sandboxID(String sandboxID) {
    
    this.sandboxID = sandboxID;
    return this;
  }

   /**
   * Identifier of the sandbox
   * @return sandboxID
  **/
  @javax.annotation.Nonnull
  public String getSandboxID() {
    return sandboxID;
  }


  public void setSandboxID(String sandboxID) {
    this.sandboxID = sandboxID;
  }


  @Deprecated
  public SandboxDetail clientID(String clientID) {
    
    this.clientID = clientID;
    return this;
  }

   /**
   * Identifier of the client
   * @return clientID
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nonnull
  public String getClientID() {
    return clientID;
  }


  @Deprecated
  public void setClientID(String clientID) {
    this.clientID = clientID;
  }


  public SandboxDetail startedAt(OffsetDateTime startedAt) {
    
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Time when the sandbox was started
   * @return startedAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }


  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }


  public SandboxDetail endAt(OffsetDateTime endAt) {
    
    this.endAt = endAt;
    return this;
  }

   /**
   * Time when the sandbox will expire
   * @return endAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getEndAt() {
    return endAt;
  }


  public void setEndAt(OffsetDateTime endAt) {
    this.endAt = endAt;
  }


  public SandboxDetail envdVersion(String envdVersion) {
    
    this.envdVersion = envdVersion;
    return this;
  }

   /**
   * Version of the envd running in the sandbox
   * @return envdVersion
  **/
  @javax.annotation.Nonnull
  public String getEnvdVersion() {
    return envdVersion;
  }


  public void setEnvdVersion(String envdVersion) {
    this.envdVersion = envdVersion;
  }


  public SandboxDetail envdAccessToken(String envdAccessToken) {
    
    this.envdAccessToken = envdAccessToken;
    return this;
  }

   /**
   * Access token used for envd communication
   * @return envdAccessToken
  **/
  @javax.annotation.Nullable
  public String getEnvdAccessToken() {
    return envdAccessToken;
  }


  public void setEnvdAccessToken(String envdAccessToken) {
    this.envdAccessToken = envdAccessToken;
  }


  public SandboxDetail allowInternetAccess(Boolean allowInternetAccess) {
    
    this.allowInternetAccess = allowInternetAccess;
    return this;
  }

   /**
   * Whether internet access was explicitly enabled or disabled for the sandbox. Null means it was not explicitly set.
   * @return allowInternetAccess
  **/
  @javax.annotation.Nullable
  public Boolean getAllowInternetAccess() {
    return allowInternetAccess;
  }


  public void setAllowInternetAccess(Boolean allowInternetAccess) {
    this.allowInternetAccess = allowInternetAccess;
  }


  public SandboxDetail domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * Base domain where the sandbox traffic is accessible
   * @return domain
  **/
  @javax.annotation.Nullable
  public String getDomain() {
    return domain;
  }


  public void setDomain(String domain) {
    this.domain = domain;
  }


  public SandboxDetail cpuCount(Integer cpuCount) {
    
    this.cpuCount = cpuCount;
    return this;
  }

   /**
   * CPU cores for the sandbox
   * minimum: 1
   * @return cpuCount
  **/
  @javax.annotation.Nonnull
  public Integer getCpuCount() {
    return cpuCount;
  }


  public void setCpuCount(Integer cpuCount) {
    this.cpuCount = cpuCount;
  }


  public SandboxDetail memoryMB(Integer memoryMB) {
    
    this.memoryMB = memoryMB;
    return this;
  }

   /**
   * Memory for the sandbox in MiB
   * minimum: 128
   * @return memoryMB
  **/
  @javax.annotation.Nonnull
  public Integer getMemoryMB() {
    return memoryMB;
  }


  public void setMemoryMB(Integer memoryMB) {
    this.memoryMB = memoryMB;
  }


  public SandboxDetail diskSizeMB(Integer diskSizeMB) {
    
    this.diskSizeMB = diskSizeMB;
    return this;
  }

   /**
   * Disk size for the sandbox in MiB
   * minimum: 0
   * @return diskSizeMB
  **/
  @javax.annotation.Nonnull
  public Integer getDiskSizeMB() {
    return diskSizeMB;
  }


  public void setDiskSizeMB(Integer diskSizeMB) {
    this.diskSizeMB = diskSizeMB;
  }


  public SandboxDetail metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public SandboxDetail putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public SandboxDetail state(SandboxState state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nonnull
  public SandboxState getState() {
    return state;
  }


  public void setState(SandboxState state) {
    this.state = state;
  }


  public SandboxDetail network(SandboxNetworkConfig network) {
    
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @javax.annotation.Nullable
  public SandboxNetworkConfig getNetwork() {
    return network;
  }


  public void setNetwork(SandboxNetworkConfig network) {
    this.network = network;
  }


  public SandboxDetail lifecycle(SandboxLifecycle lifecycle) {
    
    this.lifecycle = lifecycle;
    return this;
  }

   /**
   * Get lifecycle
   * @return lifecycle
  **/
  @javax.annotation.Nullable
  public SandboxLifecycle getLifecycle() {
    return lifecycle;
  }


  public void setLifecycle(SandboxLifecycle lifecycle) {
    this.lifecycle = lifecycle;
  }


  public SandboxDetail volumeMounts(List<SandboxVolumeMount> volumeMounts) {
    
    this.volumeMounts = volumeMounts;
    return this;
  }

  public SandboxDetail addVolumeMountsItem(SandboxVolumeMount volumeMountsItem) {
    if (this.volumeMounts == null) {
      this.volumeMounts = new ArrayList<>();
    }
    this.volumeMounts.add(volumeMountsItem);
    return this;
  }

   /**
   * Get volumeMounts
   * @return volumeMounts
  **/
  @javax.annotation.Nullable
  public List<SandboxVolumeMount> getVolumeMounts() {
    return volumeMounts;
  }


  public void setVolumeMounts(List<SandboxVolumeMount> volumeMounts) {
    this.volumeMounts = volumeMounts;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SandboxDetail instance itself
   */
  public SandboxDetail putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SandboxDetail sandboxDetail = (SandboxDetail) o;
    return Objects.equals(this.templateID, sandboxDetail.templateID) &&
        Objects.equals(this.alias, sandboxDetail.alias) &&
        Objects.equals(this.sandboxID, sandboxDetail.sandboxID) &&
        Objects.equals(this.clientID, sandboxDetail.clientID) &&
        Objects.equals(this.startedAt, sandboxDetail.startedAt) &&
        Objects.equals(this.endAt, sandboxDetail.endAt) &&
        Objects.equals(this.envdVersion, sandboxDetail.envdVersion) &&
        Objects.equals(this.envdAccessToken, sandboxDetail.envdAccessToken) &&
        Objects.equals(this.allowInternetAccess, sandboxDetail.allowInternetAccess) &&
        Objects.equals(this.domain, sandboxDetail.domain) &&
        Objects.equals(this.cpuCount, sandboxDetail.cpuCount) &&
        Objects.equals(this.memoryMB, sandboxDetail.memoryMB) &&
        Objects.equals(this.diskSizeMB, sandboxDetail.diskSizeMB) &&
        Objects.equals(this.metadata, sandboxDetail.metadata) &&
        Objects.equals(this.state, sandboxDetail.state) &&
        Objects.equals(this.network, sandboxDetail.network) &&
        Objects.equals(this.lifecycle, sandboxDetail.lifecycle) &&
        Objects.equals(this.volumeMounts, sandboxDetail.volumeMounts)&&
        Objects.equals(this.additionalProperties, sandboxDetail.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateID, alias, sandboxID, clientID, startedAt, endAt, envdVersion, envdAccessToken, allowInternetAccess, domain, cpuCount, memoryMB, diskSizeMB, metadata, state, network, lifecycle, volumeMounts, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SandboxDetail {\n");
    sb.append("    templateID: ").append(toIndentedString(templateID)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    sandboxID: ").append(toIndentedString(sandboxID)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    endAt: ").append(toIndentedString(endAt)).append("\n");
    sb.append("    envdVersion: ").append(toIndentedString(envdVersion)).append("\n");
    sb.append("    envdAccessToken: ").append(toIndentedString(envdAccessToken)).append("\n");
    sb.append("    allowInternetAccess: ").append(toIndentedString(allowInternetAccess)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    cpuCount: ").append(toIndentedString(cpuCount)).append("\n");
    sb.append("    memoryMB: ").append(toIndentedString(memoryMB)).append("\n");
    sb.append("    diskSizeMB: ").append(toIndentedString(diskSizeMB)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    lifecycle: ").append(toIndentedString(lifecycle)).append("\n");
    sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("templateID");
    openapiFields.add("alias");
    openapiFields.add("sandboxID");
    openapiFields.add("clientID");
    openapiFields.add("startedAt");
    openapiFields.add("endAt");
    openapiFields.add("envdVersion");
    openapiFields.add("envdAccessToken");
    openapiFields.add("allowInternetAccess");
    openapiFields.add("domain");
    openapiFields.add("cpuCount");
    openapiFields.add("memoryMB");
    openapiFields.add("diskSizeMB");
    openapiFields.add("metadata");
    openapiFields.add("state");
    openapiFields.add("network");
    openapiFields.add("lifecycle");
    openapiFields.add("volumeMounts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("templateID");
    openapiRequiredFields.add("sandboxID");
    openapiRequiredFields.add("clientID");
    openapiRequiredFields.add("startedAt");
    openapiRequiredFields.add("endAt");
    openapiRequiredFields.add("envdVersion");
    openapiRequiredFields.add("cpuCount");
    openapiRequiredFields.add("memoryMB");
    openapiRequiredFields.add("diskSizeMB");
    openapiRequiredFields.add("state");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SandboxDetail
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SandboxDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SandboxDetail is not found in the empty JSON string", SandboxDetail.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SandboxDetail.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("templateID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateID").toString()));
      }
      if ((jsonObj.get("alias") != null && !jsonObj.get("alias").isJsonNull()) && !jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if (!jsonObj.get("sandboxID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sandboxID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sandboxID").toString()));
      }
      if (!jsonObj.get("clientID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientID").toString()));
      }
      if (!jsonObj.get("envdVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `envdVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("envdVersion").toString()));
      }
      if ((jsonObj.get("envdAccessToken") != null && !jsonObj.get("envdAccessToken").isJsonNull()) && !jsonObj.get("envdAccessToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `envdAccessToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("envdAccessToken").toString()));
      }
      if ((jsonObj.get("domain") != null && !jsonObj.get("domain").isJsonNull()) && !jsonObj.get("domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domain").toString()));
      }
      // validate the optional field `network`
      if (jsonObj.get("network") != null && !jsonObj.get("network").isJsonNull()) {
        SandboxNetworkConfig.validateJsonObject(jsonObj.getAsJsonObject("network"));
      }
      // validate the optional field `lifecycle`
      if (jsonObj.get("lifecycle") != null && !jsonObj.get("lifecycle").isJsonNull()) {
        SandboxLifecycle.validateJsonObject(jsonObj.getAsJsonObject("lifecycle"));
      }
      if (jsonObj.get("volumeMounts") != null && !jsonObj.get("volumeMounts").isJsonNull()) {
        JsonArray jsonArrayvolumeMounts = jsonObj.getAsJsonArray("volumeMounts");
        if (jsonArrayvolumeMounts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("volumeMounts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `volumeMounts` to be an array in the JSON string but got `%s`", jsonObj.get("volumeMounts").toString()));
          }

          // validate the optional field `volumeMounts` (array)
          for (int i = 0; i < jsonArrayvolumeMounts.size(); i++) {
            SandboxVolumeMount.validateJsonObject(jsonArrayvolumeMounts.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SandboxDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SandboxDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SandboxDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SandboxDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<SandboxDetail>() {
           @Override
           public void write(JsonWriter out, SandboxDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SandboxDetail read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SandboxDetail instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SandboxDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SandboxDetail
  * @throws IOException if the JSON string is invalid with respect to SandboxDetail
  */
  public static SandboxDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SandboxDetail.class);
  }

 /**
  * Convert an instance of SandboxDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

