/*
 * E2B API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.e2b.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.openkruise.agents.client.e2b.api.invoker.JSON;

/**
 * SandboxResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T15:28:00.691+08:00[Asia/Shanghai]")
public class SandboxResponse {
  public static final String SERIALIZED_NAME_TEMPLATE_I_D = "templateID";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_I_D)
  private String templateID;

  public static final String SERIALIZED_NAME_SANDBOX_I_D = "sandboxID";
  @SerializedName(SERIALIZED_NAME_SANDBOX_I_D)
  private String sandboxID;

  public static final String SERIALIZED_NAME_ALIAS = "alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  private String alias;

  public static final String SERIALIZED_NAME_CLIENT_I_D = "clientID";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_CLIENT_I_D)
  private String clientID;

  public static final String SERIALIZED_NAME_ENVD_VERSION = "envdVersion";
  @SerializedName(SERIALIZED_NAME_ENVD_VERSION)
  private String envdVersion;

  public static final String SERIALIZED_NAME_ENVD_ACCESS_TOKEN = "envdAccessToken";
  @SerializedName(SERIALIZED_NAME_ENVD_ACCESS_TOKEN)
  private String envdAccessToken;

  public static final String SERIALIZED_NAME_TRAFFIC_ACCESS_TOKEN = "trafficAccessToken";
  @SerializedName(SERIALIZED_NAME_TRAFFIC_ACCESS_TOKEN)
  private String trafficAccessToken;

  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  private String domain;

  public SandboxResponse() {
  }

  public SandboxResponse templateID(String templateID) {
    
    this.templateID = templateID;
    return this;
  }

   /**
   * Identifier of the template from which is the sandbox created
   * @return templateID
  **/
  @javax.annotation.Nonnull
  public String getTemplateID() {
    return templateID;
  }


  public void setTemplateID(String templateID) {
    this.templateID = templateID;
  }


  public SandboxResponse sandboxID(String sandboxID) {
    
    this.sandboxID = sandboxID;
    return this;
  }

   /**
   * Identifier of the sandbox
   * @return sandboxID
  **/
  @javax.annotation.Nonnull
  public String getSandboxID() {
    return sandboxID;
  }


  public void setSandboxID(String sandboxID) {
    this.sandboxID = sandboxID;
  }


  public SandboxResponse alias(String alias) {
    
    this.alias = alias;
    return this;
  }

   /**
   * Alias of the template
   * @return alias
  **/
  @javax.annotation.Nullable
  public String getAlias() {
    return alias;
  }


  public void setAlias(String alias) {
    this.alias = alias;
  }


  @Deprecated
  public SandboxResponse clientID(String clientID) {
    
    this.clientID = clientID;
    return this;
  }

   /**
   * Identifier of the client
   * @return clientID
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nonnull
  public String getClientID() {
    return clientID;
  }


  @Deprecated
  public void setClientID(String clientID) {
    this.clientID = clientID;
  }


  public SandboxResponse envdVersion(String envdVersion) {
    
    this.envdVersion = envdVersion;
    return this;
  }

   /**
   * Version of the envd running in the sandbox
   * @return envdVersion
  **/
  @javax.annotation.Nonnull
  public String getEnvdVersion() {
    return envdVersion;
  }


  public void setEnvdVersion(String envdVersion) {
    this.envdVersion = envdVersion;
  }


  public SandboxResponse envdAccessToken(String envdAccessToken) {
    
    this.envdAccessToken = envdAccessToken;
    return this;
  }

   /**
   * Access token used for envd communication
   * @return envdAccessToken
  **/
  @javax.annotation.Nullable
  public String getEnvdAccessToken() {
    return envdAccessToken;
  }


  public void setEnvdAccessToken(String envdAccessToken) {
    this.envdAccessToken = envdAccessToken;
  }


  public SandboxResponse trafficAccessToken(String trafficAccessToken) {
    
    this.trafficAccessToken = trafficAccessToken;
    return this;
  }

   /**
   * Token required for accessing sandbox via proxy.
   * @return trafficAccessToken
  **/
  @javax.annotation.Nullable
  public String getTrafficAccessToken() {
    return trafficAccessToken;
  }


  public void setTrafficAccessToken(String trafficAccessToken) {
    this.trafficAccessToken = trafficAccessToken;
  }


  public SandboxResponse domain(String domain) {
    
    this.domain = domain;
    return this;
  }

   /**
   * Base domain where the sandbox traffic is accessible
   * @return domain
  **/
  @javax.annotation.Nullable
  public String getDomain() {
    return domain;
  }


  public void setDomain(String domain) {
    this.domain = domain;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SandboxResponse instance itself
   */
  public SandboxResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SandboxResponse sandboxResponse = (SandboxResponse) o;
    return Objects.equals(this.templateID, sandboxResponse.templateID) &&
        Objects.equals(this.sandboxID, sandboxResponse.sandboxID) &&
        Objects.equals(this.alias, sandboxResponse.alias) &&
        Objects.equals(this.clientID, sandboxResponse.clientID) &&
        Objects.equals(this.envdVersion, sandboxResponse.envdVersion) &&
        Objects.equals(this.envdAccessToken, sandboxResponse.envdAccessToken) &&
        Objects.equals(this.trafficAccessToken, sandboxResponse.trafficAccessToken) &&
        Objects.equals(this.domain, sandboxResponse.domain)&&
        Objects.equals(this.additionalProperties, sandboxResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateID, sandboxID, alias, clientID, envdVersion, envdAccessToken, trafficAccessToken, domain, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SandboxResponse {\n");
    sb.append("    templateID: ").append(toIndentedString(templateID)).append("\n");
    sb.append("    sandboxID: ").append(toIndentedString(sandboxID)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    envdVersion: ").append(toIndentedString(envdVersion)).append("\n");
    sb.append("    envdAccessToken: ").append(toIndentedString(envdAccessToken)).append("\n");
    sb.append("    trafficAccessToken: ").append(toIndentedString(trafficAccessToken)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("templateID");
    openapiFields.add("sandboxID");
    openapiFields.add("alias");
    openapiFields.add("clientID");
    openapiFields.add("envdVersion");
    openapiFields.add("envdAccessToken");
    openapiFields.add("trafficAccessToken");
    openapiFields.add("domain");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("templateID");
    openapiRequiredFields.add("sandboxID");
    openapiRequiredFields.add("clientID");
    openapiRequiredFields.add("envdVersion");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SandboxResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SandboxResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SandboxResponse is not found in the empty JSON string", SandboxResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SandboxResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("templateID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateID").toString()));
      }
      if (!jsonObj.get("sandboxID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sandboxID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sandboxID").toString()));
      }
      if ((jsonObj.get("alias") != null && !jsonObj.get("alias").isJsonNull()) && !jsonObj.get("alias").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alias` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alias").toString()));
      }
      if (!jsonObj.get("clientID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientID").toString()));
      }
      if (!jsonObj.get("envdVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `envdVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("envdVersion").toString()));
      }
      if ((jsonObj.get("envdAccessToken") != null && !jsonObj.get("envdAccessToken").isJsonNull()) && !jsonObj.get("envdAccessToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `envdAccessToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("envdAccessToken").toString()));
      }
      if ((jsonObj.get("trafficAccessToken") != null && !jsonObj.get("trafficAccessToken").isJsonNull()) && !jsonObj.get("trafficAccessToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trafficAccessToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trafficAccessToken").toString()));
      }
      if ((jsonObj.get("domain") != null && !jsonObj.get("domain").isJsonNull()) && !jsonObj.get("domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domain").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SandboxResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SandboxResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SandboxResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SandboxResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SandboxResponse>() {
           @Override
           public void write(JsonWriter out, SandboxResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SandboxResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SandboxResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SandboxResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SandboxResponse
  * @throws IOException if the JSON string is invalid with respect to SandboxResponse
  */
  public static SandboxResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SandboxResponse.class);
  }

 /**
  * Convert an instance of SandboxResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

