/*
 * E2B API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.e2b.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.agents.client.e2b.api.models.TemplateBuild;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.openkruise.agents.client.e2b.api.invoker.JSON;

/**
 * TemplateWithBuilds
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T15:28:00.691+08:00[Asia/Shanghai]")
public class TemplateWithBuilds {
  public static final String SERIALIZED_NAME_TEMPLATE_I_D = "templateID";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_I_D)
  private String templateID;

  public static final String SERIALIZED_NAME_PUBLIC = "public";
  @SerializedName(SERIALIZED_NAME_PUBLIC)
  private Boolean _public;

  public static final String SERIALIZED_NAME_ALIASES = "aliases";
  @Deprecated
  @SerializedName(SERIALIZED_NAME_ALIASES)
  private List<String> aliases = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAMES = "names";
  @SerializedName(SERIALIZED_NAME_NAMES)
  private List<String> names = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_LAST_SPAWNED_AT = "lastSpawnedAt";
  @SerializedName(SERIALIZED_NAME_LAST_SPAWNED_AT)
  private OffsetDateTime lastSpawnedAt;

  public static final String SERIALIZED_NAME_SPAWN_COUNT = "spawnCount";
  @SerializedName(SERIALIZED_NAME_SPAWN_COUNT)
  private Long spawnCount;

  public static final String SERIALIZED_NAME_BUILDS = "builds";
  @SerializedName(SERIALIZED_NAME_BUILDS)
  private List<TemplateBuild> builds = new ArrayList<>();

  public TemplateWithBuilds() {
  }

  public TemplateWithBuilds templateID(String templateID) {
    
    this.templateID = templateID;
    return this;
  }

   /**
   * Identifier of the template
   * @return templateID
  **/
  @javax.annotation.Nonnull
  public String getTemplateID() {
    return templateID;
  }


  public void setTemplateID(String templateID) {
    this.templateID = templateID;
  }


  public TemplateWithBuilds _public(Boolean _public) {
    
    this._public = _public;
    return this;
  }

   /**
   * Whether the template is public or only accessible by the team
   * @return _public
  **/
  @javax.annotation.Nonnull
  public Boolean getPublic() {
    return _public;
  }


  public void setPublic(Boolean _public) {
    this._public = _public;
  }


  @Deprecated
  public TemplateWithBuilds aliases(List<String> aliases) {
    
    this.aliases = aliases;
    return this;
  }

  public TemplateWithBuilds addAliasesItem(String aliasesItem) {
    if (this.aliases == null) {
      this.aliases = new ArrayList<>();
    }
    this.aliases.add(aliasesItem);
    return this;
  }

   /**
   * Aliases of the template
   * @return aliases
   * @deprecated
  **/
  @Deprecated
  @javax.annotation.Nonnull
  public List<String> getAliases() {
    return aliases;
  }


  @Deprecated
  public void setAliases(List<String> aliases) {
    this.aliases = aliases;
  }


  public TemplateWithBuilds names(List<String> names) {
    
    this.names = names;
    return this;
  }

  public TemplateWithBuilds addNamesItem(String namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * Names of the template (namespace/alias format when namespaced)
   * @return names
  **/
  @javax.annotation.Nonnull
  public List<String> getNames() {
    return names;
  }


  public void setNames(List<String> names) {
    this.names = names;
  }


  public TemplateWithBuilds createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Time when the template was created
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TemplateWithBuilds updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Time when the template was last updated
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TemplateWithBuilds lastSpawnedAt(OffsetDateTime lastSpawnedAt) {
    
    this.lastSpawnedAt = lastSpawnedAt;
    return this;
  }

   /**
   * Time when the template was last used
   * @return lastSpawnedAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getLastSpawnedAt() {
    return lastSpawnedAt;
  }


  public void setLastSpawnedAt(OffsetDateTime lastSpawnedAt) {
    this.lastSpawnedAt = lastSpawnedAt;
  }


  public TemplateWithBuilds spawnCount(Long spawnCount) {
    
    this.spawnCount = spawnCount;
    return this;
  }

   /**
   * Number of times the template was used
   * @return spawnCount
  **/
  @javax.annotation.Nonnull
  public Long getSpawnCount() {
    return spawnCount;
  }


  public void setSpawnCount(Long spawnCount) {
    this.spawnCount = spawnCount;
  }


  public TemplateWithBuilds builds(List<TemplateBuild> builds) {
    
    this.builds = builds;
    return this;
  }

  public TemplateWithBuilds addBuildsItem(TemplateBuild buildsItem) {
    if (this.builds == null) {
      this.builds = new ArrayList<>();
    }
    this.builds.add(buildsItem);
    return this;
  }

   /**
   * List of builds for the template
   * @return builds
  **/
  @javax.annotation.Nonnull
  public List<TemplateBuild> getBuilds() {
    return builds;
  }


  public void setBuilds(List<TemplateBuild> builds) {
    this.builds = builds;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateWithBuilds instance itself
   */
  public TemplateWithBuilds putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateWithBuilds templateWithBuilds = (TemplateWithBuilds) o;
    return Objects.equals(this.templateID, templateWithBuilds.templateID) &&
        Objects.equals(this._public, templateWithBuilds._public) &&
        Objects.equals(this.aliases, templateWithBuilds.aliases) &&
        Objects.equals(this.names, templateWithBuilds.names) &&
        Objects.equals(this.createdAt, templateWithBuilds.createdAt) &&
        Objects.equals(this.updatedAt, templateWithBuilds.updatedAt) &&
        Objects.equals(this.lastSpawnedAt, templateWithBuilds.lastSpawnedAt) &&
        Objects.equals(this.spawnCount, templateWithBuilds.spawnCount) &&
        Objects.equals(this.builds, templateWithBuilds.builds)&&
        Objects.equals(this.additionalProperties, templateWithBuilds.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateID, _public, aliases, names, createdAt, updatedAt, lastSpawnedAt, spawnCount, builds, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateWithBuilds {\n");
    sb.append("    templateID: ").append(toIndentedString(templateID)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    lastSpawnedAt: ").append(toIndentedString(lastSpawnedAt)).append("\n");
    sb.append("    spawnCount: ").append(toIndentedString(spawnCount)).append("\n");
    sb.append("    builds: ").append(toIndentedString(builds)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("templateID");
    openapiFields.add("public");
    openapiFields.add("aliases");
    openapiFields.add("names");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("lastSpawnedAt");
    openapiFields.add("spawnCount");
    openapiFields.add("builds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("templateID");
    openapiRequiredFields.add("public");
    openapiRequiredFields.add("aliases");
    openapiRequiredFields.add("names");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
    openapiRequiredFields.add("lastSpawnedAt");
    openapiRequiredFields.add("spawnCount");
    openapiRequiredFields.add("builds");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateWithBuilds
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateWithBuilds.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateWithBuilds is not found in the empty JSON string", TemplateWithBuilds.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TemplateWithBuilds.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("templateID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateID").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("aliases") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("aliases").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `aliases` to be an array in the JSON string but got `%s`", jsonObj.get("aliases").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("names") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("names").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `names` to be an array in the JSON string but got `%s`", jsonObj.get("names").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("builds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `builds` to be an array in the JSON string but got `%s`", jsonObj.get("builds").toString()));
      }

      JsonArray jsonArraybuilds = jsonObj.getAsJsonArray("builds");
      // validate the required field `builds` (array)
      for (int i = 0; i < jsonArraybuilds.size(); i++) {
        TemplateBuild.validateJsonObject(jsonArraybuilds.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateWithBuilds.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateWithBuilds' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateWithBuilds> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateWithBuilds.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateWithBuilds>() {
           @Override
           public void write(JsonWriter out, TemplateWithBuilds value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateWithBuilds read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateWithBuilds instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateWithBuilds given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateWithBuilds
  * @throws IOException if the JSON string is invalid with respect to TemplateWithBuilds
  */
  public static TemplateWithBuilds fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateWithBuilds.class);
  }

 /**
  * Convert an instance of TemplateWithBuilds to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

