/*
 * E2B API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openkruise.agents.client.e2b.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.agents.client.e2b.api.models.TeamUser;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.openkruise.agents.client.e2b.api.invoker.JSON;

/**
 * TemplateLegacy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T15:28:00.691+08:00[Asia/Shanghai]")
public class TemplateLegacy {
  public static final String SERIALIZED_NAME_TEMPLATE_I_D = "templateID";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_I_D)
  private String templateID;

  public static final String SERIALIZED_NAME_BUILD_I_D = "buildID";
  @SerializedName(SERIALIZED_NAME_BUILD_I_D)
  private String buildID;

  public static final String SERIALIZED_NAME_CPU_COUNT = "cpuCount";
  @SerializedName(SERIALIZED_NAME_CPU_COUNT)
  private Integer cpuCount;

  public static final String SERIALIZED_NAME_MEMORY_M_B = "memoryMB";
  @SerializedName(SERIALIZED_NAME_MEMORY_M_B)
  private Integer memoryMB;

  public static final String SERIALIZED_NAME_DISK_SIZE_M_B = "diskSizeMB";
  @SerializedName(SERIALIZED_NAME_DISK_SIZE_M_B)
  private Integer diskSizeMB;

  public static final String SERIALIZED_NAME_PUBLIC = "public";
  @SerializedName(SERIALIZED_NAME_PUBLIC)
  private Boolean _public;

  public static final String SERIALIZED_NAME_ALIASES = "aliases";
  @SerializedName(SERIALIZED_NAME_ALIASES)
  private List<String> aliases = new ArrayList<>();

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private TeamUser createdBy;

  public static final String SERIALIZED_NAME_LAST_SPAWNED_AT = "lastSpawnedAt";
  @SerializedName(SERIALIZED_NAME_LAST_SPAWNED_AT)
  private OffsetDateTime lastSpawnedAt;

  public static final String SERIALIZED_NAME_SPAWN_COUNT = "spawnCount";
  @SerializedName(SERIALIZED_NAME_SPAWN_COUNT)
  private Long spawnCount;

  public static final String SERIALIZED_NAME_BUILD_COUNT = "buildCount";
  @SerializedName(SERIALIZED_NAME_BUILD_COUNT)
  private Integer buildCount;

  public static final String SERIALIZED_NAME_ENVD_VERSION = "envdVersion";
  @SerializedName(SERIALIZED_NAME_ENVD_VERSION)
  private String envdVersion;

  public TemplateLegacy() {
  }

  public TemplateLegacy templateID(String templateID) {
    
    this.templateID = templateID;
    return this;
  }

   /**
   * Identifier of the template
   * @return templateID
  **/
  @javax.annotation.Nonnull
  public String getTemplateID() {
    return templateID;
  }


  public void setTemplateID(String templateID) {
    this.templateID = templateID;
  }


  public TemplateLegacy buildID(String buildID) {
    
    this.buildID = buildID;
    return this;
  }

   /**
   * Identifier of the last successful build for given template
   * @return buildID
  **/
  @javax.annotation.Nonnull
  public String getBuildID() {
    return buildID;
  }


  public void setBuildID(String buildID) {
    this.buildID = buildID;
  }


  public TemplateLegacy cpuCount(Integer cpuCount) {
    
    this.cpuCount = cpuCount;
    return this;
  }

   /**
   * CPU cores for the sandbox
   * minimum: 1
   * @return cpuCount
  **/
  @javax.annotation.Nonnull
  public Integer getCpuCount() {
    return cpuCount;
  }


  public void setCpuCount(Integer cpuCount) {
    this.cpuCount = cpuCount;
  }


  public TemplateLegacy memoryMB(Integer memoryMB) {
    
    this.memoryMB = memoryMB;
    return this;
  }

   /**
   * Memory for the sandbox in MiB
   * minimum: 128
   * @return memoryMB
  **/
  @javax.annotation.Nonnull
  public Integer getMemoryMB() {
    return memoryMB;
  }


  public void setMemoryMB(Integer memoryMB) {
    this.memoryMB = memoryMB;
  }


  public TemplateLegacy diskSizeMB(Integer diskSizeMB) {
    
    this.diskSizeMB = diskSizeMB;
    return this;
  }

   /**
   * Disk size for the sandbox in MiB
   * minimum: 0
   * @return diskSizeMB
  **/
  @javax.annotation.Nonnull
  public Integer getDiskSizeMB() {
    return diskSizeMB;
  }


  public void setDiskSizeMB(Integer diskSizeMB) {
    this.diskSizeMB = diskSizeMB;
  }


  public TemplateLegacy _public(Boolean _public) {
    
    this._public = _public;
    return this;
  }

   /**
   * Whether the template is public or only accessible by the team
   * @return _public
  **/
  @javax.annotation.Nonnull
  public Boolean getPublic() {
    return _public;
  }


  public void setPublic(Boolean _public) {
    this._public = _public;
  }


  public TemplateLegacy aliases(List<String> aliases) {
    
    this.aliases = aliases;
    return this;
  }

  public TemplateLegacy addAliasesItem(String aliasesItem) {
    if (this.aliases == null) {
      this.aliases = new ArrayList<>();
    }
    this.aliases.add(aliasesItem);
    return this;
  }

   /**
   * Aliases of the template
   * @return aliases
  **/
  @javax.annotation.Nonnull
  public List<String> getAliases() {
    return aliases;
  }


  public void setAliases(List<String> aliases) {
    this.aliases = aliases;
  }


  public TemplateLegacy createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Time when the template was created
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TemplateLegacy updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Time when the template was last updated
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TemplateLegacy createdBy(TeamUser createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  public TeamUser getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(TeamUser createdBy) {
    this.createdBy = createdBy;
  }


  public TemplateLegacy lastSpawnedAt(OffsetDateTime lastSpawnedAt) {
    
    this.lastSpawnedAt = lastSpawnedAt;
    return this;
  }

   /**
   * Time when the template was last used
   * @return lastSpawnedAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getLastSpawnedAt() {
    return lastSpawnedAt;
  }


  public void setLastSpawnedAt(OffsetDateTime lastSpawnedAt) {
    this.lastSpawnedAt = lastSpawnedAt;
  }


  public TemplateLegacy spawnCount(Long spawnCount) {
    
    this.spawnCount = spawnCount;
    return this;
  }

   /**
   * Number of times the template was used
   * @return spawnCount
  **/
  @javax.annotation.Nonnull
  public Long getSpawnCount() {
    return spawnCount;
  }


  public void setSpawnCount(Long spawnCount) {
    this.spawnCount = spawnCount;
  }


  public TemplateLegacy buildCount(Integer buildCount) {
    
    this.buildCount = buildCount;
    return this;
  }

   /**
   * Number of times the template was built
   * @return buildCount
  **/
  @javax.annotation.Nonnull
  public Integer getBuildCount() {
    return buildCount;
  }


  public void setBuildCount(Integer buildCount) {
    this.buildCount = buildCount;
  }


  public TemplateLegacy envdVersion(String envdVersion) {
    
    this.envdVersion = envdVersion;
    return this;
  }

   /**
   * Version of the envd running in the sandbox
   * @return envdVersion
  **/
  @javax.annotation.Nonnull
  public String getEnvdVersion() {
    return envdVersion;
  }


  public void setEnvdVersion(String envdVersion) {
    this.envdVersion = envdVersion;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateLegacy instance itself
   */
  public TemplateLegacy putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateLegacy templateLegacy = (TemplateLegacy) o;
    return Objects.equals(this.templateID, templateLegacy.templateID) &&
        Objects.equals(this.buildID, templateLegacy.buildID) &&
        Objects.equals(this.cpuCount, templateLegacy.cpuCount) &&
        Objects.equals(this.memoryMB, templateLegacy.memoryMB) &&
        Objects.equals(this.diskSizeMB, templateLegacy.diskSizeMB) &&
        Objects.equals(this._public, templateLegacy._public) &&
        Objects.equals(this.aliases, templateLegacy.aliases) &&
        Objects.equals(this.createdAt, templateLegacy.createdAt) &&
        Objects.equals(this.updatedAt, templateLegacy.updatedAt) &&
        Objects.equals(this.createdBy, templateLegacy.createdBy) &&
        Objects.equals(this.lastSpawnedAt, templateLegacy.lastSpawnedAt) &&
        Objects.equals(this.spawnCount, templateLegacy.spawnCount) &&
        Objects.equals(this.buildCount, templateLegacy.buildCount) &&
        Objects.equals(this.envdVersion, templateLegacy.envdVersion)&&
        Objects.equals(this.additionalProperties, templateLegacy.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateID, buildID, cpuCount, memoryMB, diskSizeMB, _public, aliases, createdAt, updatedAt, createdBy, lastSpawnedAt, spawnCount, buildCount, envdVersion, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateLegacy {\n");
    sb.append("    templateID: ").append(toIndentedString(templateID)).append("\n");
    sb.append("    buildID: ").append(toIndentedString(buildID)).append("\n");
    sb.append("    cpuCount: ").append(toIndentedString(cpuCount)).append("\n");
    sb.append("    memoryMB: ").append(toIndentedString(memoryMB)).append("\n");
    sb.append("    diskSizeMB: ").append(toIndentedString(diskSizeMB)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    lastSpawnedAt: ").append(toIndentedString(lastSpawnedAt)).append("\n");
    sb.append("    spawnCount: ").append(toIndentedString(spawnCount)).append("\n");
    sb.append("    buildCount: ").append(toIndentedString(buildCount)).append("\n");
    sb.append("    envdVersion: ").append(toIndentedString(envdVersion)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("templateID");
    openapiFields.add("buildID");
    openapiFields.add("cpuCount");
    openapiFields.add("memoryMB");
    openapiFields.add("diskSizeMB");
    openapiFields.add("public");
    openapiFields.add("aliases");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("createdBy");
    openapiFields.add("lastSpawnedAt");
    openapiFields.add("spawnCount");
    openapiFields.add("buildCount");
    openapiFields.add("envdVersion");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("templateID");
    openapiRequiredFields.add("buildID");
    openapiRequiredFields.add("cpuCount");
    openapiRequiredFields.add("memoryMB");
    openapiRequiredFields.add("diskSizeMB");
    openapiRequiredFields.add("public");
    openapiRequiredFields.add("aliases");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
    openapiRequiredFields.add("createdBy");
    openapiRequiredFields.add("lastSpawnedAt");
    openapiRequiredFields.add("spawnCount");
    openapiRequiredFields.add("buildCount");
    openapiRequiredFields.add("envdVersion");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateLegacy
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateLegacy.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateLegacy is not found in the empty JSON string", TemplateLegacy.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TemplateLegacy.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("templateID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateID").toString()));
      }
      if (!jsonObj.get("buildID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buildID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buildID").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("aliases") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("aliases").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `aliases` to be an array in the JSON string but got `%s`", jsonObj.get("aliases").toString()));
      }
      // validate the required field `createdBy`
      TeamUser.validateJsonObject(jsonObj.getAsJsonObject("createdBy"));
      if (!jsonObj.get("envdVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `envdVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("envdVersion").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateLegacy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateLegacy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateLegacy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateLegacy.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateLegacy>() {
           @Override
           public void write(JsonWriter out, TemplateLegacy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateLegacy read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateLegacy instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateLegacy given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateLegacy
  * @throws IOException if the JSON string is invalid with respect to TemplateLegacy
  */
  public static TemplateLegacy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateLegacy.class);
  }

 /**
  * Convert an instance of TemplateLegacy to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

