# generated by datamodel-codegen:
#   filename:  sandboxtemplate_schema.json
#   timestamp: 2026-08-27T10:23:20+00:00

from __future__ import annotations

from enum import StrEnum

from kubernetes.client.models import (
    V1ObjectMeta,
    V1PersistentVolumeClaim,
    V1PodTemplateSpec,
)
from pydantic import BaseModel, ConfigDict


class HibernateStrategy(BaseModel):
    """
    HibernateStrategy configures the storage medium for hibernate state.
    Only effective when Type is Hibernate.
    """

    type: str | None = None
    """
    Type selects the storage medium for hibernate state.
    """


class PauseStrategy(BaseModel):
    """
    PauseStrategy configures how sandboxes created from this template are
    paused when their spec.paused is true. It is only informational when a
    SandboxSet uses spec.templateRef: SandboxSetSpec.PauseStrategy always
    takes precedence and is what actually reaches created Sandboxes.
    """

    hibernateStrategy: HibernateStrategy | None = None
    """
    HibernateStrategy configures the storage medium for hibernate state.
    Only effective when Type is Hibernate.
    """
    type: Type | None = None
    """
    Type selects the pause mechanism.
    """


class Runtime(BaseModel):
    name: str


class SandboxTemplate(BaseModel):
    """
    SandboxSet is the Schema for the sandboxsets API, which is an advanced workload for managing sandboxes.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object.
    Servers should convert recognized schemas to the latest internal value, and
    may reject unrecognized values.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents.
    Servers may infer this from the endpoint the client submits requests to.
    Cannot be updated.
    In CamelCase.
    More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: V1ObjectMeta | None = None
    spec: Spec
    """
    spec defines the desired state of SandboxSet
    """


class Spec(BaseModel):
    """
    spec defines the desired state of SandboxSet
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    pauseStrategy: PauseStrategy | None = None
    """
    PauseStrategy configures how sandboxes created from this template are
    paused when their spec.paused is true. It is only informational when a
    SandboxSet uses spec.templateRef: SandboxSetSpec.PauseStrategy always
    takes precedence and is what actually reaches created Sandboxes.
    """
    persistentContents: list[str] | None = None
    """
    PersistentContents indicates resume pod with persistent content, Enum: ip, memory, filesystem
    """
    runtimes: list[Runtime] | None = None
    """
    Runtimes - Runtime configuration for sandbox object
    """
    template: V1PodTemplateSpec | None = None
    """
    Template describes the pods that will be created.
    Template is mutual exclusive with TemplateRef
    """
    volumeClaimTemplates: list[V1PersistentVolumeClaim] | None = None
    """
    VolumeClaimTemplates is a list of PVC templates to create for this Sandbox.
    """


class Type(StrEnum):
    """
    Type selects the pause mechanism.
    """

    Stop = "Stop"
    Hibernate = "Hibernate"
