/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	agentsv1alpha1 "github.com/openkruise/agents-api/agents/v1alpha1"
	scheme "github.com/openkruise/agents-api/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GlobalSecurityProfilesGetter has a method to return a GlobalSecurityProfileInterface.
// A group's client should implement this interface.
type GlobalSecurityProfilesGetter interface {
	GlobalSecurityProfiles() GlobalSecurityProfileInterface
}

// GlobalSecurityProfileInterface has methods to work with GlobalSecurityProfile resources.
type GlobalSecurityProfileInterface interface {
	Create(ctx context.Context, globalSecurityProfile *agentsv1alpha1.GlobalSecurityProfile, opts v1.CreateOptions) (*agentsv1alpha1.GlobalSecurityProfile, error)
	Update(ctx context.Context, globalSecurityProfile *agentsv1alpha1.GlobalSecurityProfile, opts v1.UpdateOptions) (*agentsv1alpha1.GlobalSecurityProfile, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, globalSecurityProfile *agentsv1alpha1.GlobalSecurityProfile, opts v1.UpdateOptions) (*agentsv1alpha1.GlobalSecurityProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*agentsv1alpha1.GlobalSecurityProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*agentsv1alpha1.GlobalSecurityProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *agentsv1alpha1.GlobalSecurityProfile, err error)
	GlobalSecurityProfileExpansion
}

// globalSecurityProfiles implements GlobalSecurityProfileInterface
type globalSecurityProfiles struct {
	*gentype.ClientWithList[*agentsv1alpha1.GlobalSecurityProfile, *agentsv1alpha1.GlobalSecurityProfileList]
}

// newGlobalSecurityProfiles returns a GlobalSecurityProfiles
func newGlobalSecurityProfiles(c *AgentsV1alpha1Client) *globalSecurityProfiles {
	return &globalSecurityProfiles{
		gentype.NewClientWithList[*agentsv1alpha1.GlobalSecurityProfile, *agentsv1alpha1.GlobalSecurityProfileList](
			"globalsecurityprofiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *agentsv1alpha1.GlobalSecurityProfile { return &agentsv1alpha1.GlobalSecurityProfile{} },
			func() *agentsv1alpha1.GlobalSecurityProfileList { return &agentsv1alpha1.GlobalSecurityProfileList{} },
		),
	}
}
