/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SandboxesSandboxIDRefreshesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxesSandboxIDRefreshesPostRequest{}

// SandboxesSandboxIDRefreshesPostRequest struct for SandboxesSandboxIDRefreshesPostRequest
type SandboxesSandboxIDRefreshesPostRequest struct {
	// Duration for which the sandbox should be kept alive in seconds
	Duration *int32 `json:"duration,omitempty"`
}

// NewSandboxesSandboxIDRefreshesPostRequest instantiates a new SandboxesSandboxIDRefreshesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxesSandboxIDRefreshesPostRequest() *SandboxesSandboxIDRefreshesPostRequest {
	this := SandboxesSandboxIDRefreshesPostRequest{}
	return &this
}

// NewSandboxesSandboxIDRefreshesPostRequestWithDefaults instantiates a new SandboxesSandboxIDRefreshesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxesSandboxIDRefreshesPostRequestWithDefaults() *SandboxesSandboxIDRefreshesPostRequest {
	this := SandboxesSandboxIDRefreshesPostRequest{}
	return &this
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *SandboxesSandboxIDRefreshesPostRequest) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxesSandboxIDRefreshesPostRequest) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *SandboxesSandboxIDRefreshesPostRequest) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *SandboxesSandboxIDRefreshesPostRequest) SetDuration(v int32) {
	o.Duration = &v
}

func (o SandboxesSandboxIDRefreshesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxesSandboxIDRefreshesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableSandboxesSandboxIDRefreshesPostRequest struct {
	value *SandboxesSandboxIDRefreshesPostRequest
	isSet bool
}

func (v NullableSandboxesSandboxIDRefreshesPostRequest) Get() *SandboxesSandboxIDRefreshesPostRequest {
	return v.value
}

func (v *NullableSandboxesSandboxIDRefreshesPostRequest) Set(val *SandboxesSandboxIDRefreshesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxesSandboxIDRefreshesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxesSandboxIDRefreshesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxesSandboxIDRefreshesPostRequest(val *SandboxesSandboxIDRefreshesPostRequest) *NullableSandboxesSandboxIDRefreshesPostRequest {
	return &NullableSandboxesSandboxIDRefreshesPostRequest{value: val, isSet: true}
}

func (v NullableSandboxesSandboxIDRefreshesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxesSandboxIDRefreshesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
