/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the DiskMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiskMetrics{}

// DiskMetrics struct for DiskMetrics
type DiskMetrics struct {
	// Mount point of the disk
	MountPoint string `json:"mountPoint"`
	// Device name
	Device string `json:"device"`
	// Filesystem type (e.g., ext4, xfs)
	FilesystemType string `json:"filesystemType"`
	// Used space in bytes
	UsedBytes int32 `json:"usedBytes"`
	// Total space in bytes
	TotalBytes int32 `json:"totalBytes"`
}

// NewDiskMetrics instantiates a new DiskMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiskMetrics(mountPoint string, device string, filesystemType string, usedBytes int32, totalBytes int32) *DiskMetrics {
	this := DiskMetrics{}
	this.MountPoint = mountPoint
	this.Device = device
	this.FilesystemType = filesystemType
	this.UsedBytes = usedBytes
	this.TotalBytes = totalBytes
	return &this
}

// NewDiskMetricsWithDefaults instantiates a new DiskMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiskMetricsWithDefaults() *DiskMetrics {
	this := DiskMetrics{}
	return &this
}

// GetMountPoint returns the MountPoint field value
func (o *DiskMetrics) GetMountPoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MountPoint
}

// GetMountPointOk returns a tuple with the MountPoint field value
// and a boolean to check if the value has been set.
func (o *DiskMetrics) GetMountPointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MountPoint, true
}

// SetMountPoint sets field value
func (o *DiskMetrics) SetMountPoint(v string) {
	o.MountPoint = v
}

// GetDevice returns the Device field value
func (o *DiskMetrics) GetDevice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *DiskMetrics) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *DiskMetrics) SetDevice(v string) {
	o.Device = v
}

// GetFilesystemType returns the FilesystemType field value
func (o *DiskMetrics) GetFilesystemType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilesystemType
}

// GetFilesystemTypeOk returns a tuple with the FilesystemType field value
// and a boolean to check if the value has been set.
func (o *DiskMetrics) GetFilesystemTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilesystemType, true
}

// SetFilesystemType sets field value
func (o *DiskMetrics) SetFilesystemType(v string) {
	o.FilesystemType = v
}

// GetUsedBytes returns the UsedBytes field value
func (o *DiskMetrics) GetUsedBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UsedBytes
}

// GetUsedBytesOk returns a tuple with the UsedBytes field value
// and a boolean to check if the value has been set.
func (o *DiskMetrics) GetUsedBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedBytes, true
}

// SetUsedBytes sets field value
func (o *DiskMetrics) SetUsedBytes(v int32) {
	o.UsedBytes = v
}

// GetTotalBytes returns the TotalBytes field value
func (o *DiskMetrics) GetTotalBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalBytes
}

// GetTotalBytesOk returns a tuple with the TotalBytes field value
// and a boolean to check if the value has been set.
func (o *DiskMetrics) GetTotalBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalBytes, true
}

// SetTotalBytes sets field value
func (o *DiskMetrics) SetTotalBytes(v int32) {
	o.TotalBytes = v
}

func (o DiskMetrics) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiskMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mountPoint"] = o.MountPoint
	toSerialize["device"] = o.Device
	toSerialize["filesystemType"] = o.FilesystemType
	toSerialize["usedBytes"] = o.UsedBytes
	toSerialize["totalBytes"] = o.TotalBytes
	return toSerialize, nil
}

type NullableDiskMetrics struct {
	value *DiskMetrics
	isSet bool
}

func (v NullableDiskMetrics) Get() *DiskMetrics {
	return v.value
}

func (v *NullableDiskMetrics) Set(val *DiskMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskMetrics(val *DiskMetrics) *NullableDiskMetrics {
	return &NullableDiskMetrics{value: val, isSet: true}
}

func (v NullableDiskMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
