/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TemplateBuildLogsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateBuildLogsResponse{}

// TemplateBuildLogsResponse struct for TemplateBuildLogsResponse
type TemplateBuildLogsResponse struct {
	// Build logs structured
	Logs []BuildLogEntry `json:"logs"`
}

// NewTemplateBuildLogsResponse instantiates a new TemplateBuildLogsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateBuildLogsResponse(logs []BuildLogEntry) *TemplateBuildLogsResponse {
	this := TemplateBuildLogsResponse{}
	this.Logs = logs
	return &this
}

// NewTemplateBuildLogsResponseWithDefaults instantiates a new TemplateBuildLogsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateBuildLogsResponseWithDefaults() *TemplateBuildLogsResponse {
	this := TemplateBuildLogsResponse{}
	return &this
}

// GetLogs returns the Logs field value
func (o *TemplateBuildLogsResponse) GetLogs() []BuildLogEntry {
	if o == nil {
		var ret []BuildLogEntry
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *TemplateBuildLogsResponse) GetLogsOk() ([]BuildLogEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs, true
}

// SetLogs sets field value
func (o *TemplateBuildLogsResponse) SetLogs(v []BuildLogEntry) {
	o.Logs = v
}

func (o TemplateBuildLogsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateBuildLogsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logs"] = o.Logs
	return toSerialize, nil
}

type NullableTemplateBuildLogsResponse struct {
	value *TemplateBuildLogsResponse
	isSet bool
}

func (v NullableTemplateBuildLogsResponse) Get() *TemplateBuildLogsResponse {
	return v.value
}

func (v *NullableTemplateBuildLogsResponse) Set(val *TemplateBuildLogsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateBuildLogsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateBuildLogsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateBuildLogsResponse(val *TemplateBuildLogsResponse) *NullableTemplateBuildLogsResponse {
	return &NullableTemplateBuildLogsResponse{value: val, isSet: true}
}

func (v NullableTemplateBuildLogsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateBuildLogsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
