/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ResumedSandbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResumedSandbox{}

// ResumedSandbox struct for ResumedSandbox
type ResumedSandbox struct {
	// Time to live for the sandbox in seconds.
	Timeout *int32 `json:"timeout,omitempty"`
	// Automatically pauses the sandbox after the timeout
	// Deprecated
	AutoPause *bool `json:"autoPause,omitempty"`
}

// NewResumedSandbox instantiates a new ResumedSandbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResumedSandbox() *ResumedSandbox {
	this := ResumedSandbox{}
	var timeout int32 = 15
	this.Timeout = &timeout
	return &this
}

// NewResumedSandboxWithDefaults instantiates a new ResumedSandbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResumedSandboxWithDefaults() *ResumedSandbox {
	this := ResumedSandbox{}
	var timeout int32 = 15
	this.Timeout = &timeout
	return &this
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ResumedSandbox) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResumedSandbox) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ResumedSandbox) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *ResumedSandbox) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetAutoPause returns the AutoPause field value if set, zero value otherwise.
// Deprecated
func (o *ResumedSandbox) GetAutoPause() bool {
	if o == nil || IsNil(o.AutoPause) {
		var ret bool
		return ret
	}
	return *o.AutoPause
}

// GetAutoPauseOk returns a tuple with the AutoPause field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ResumedSandbox) GetAutoPauseOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoPause) {
		return nil, false
	}
	return o.AutoPause, true
}

// HasAutoPause returns a boolean if a field has been set.
func (o *ResumedSandbox) HasAutoPause() bool {
	if o != nil && !IsNil(o.AutoPause) {
		return true
	}

	return false
}

// SetAutoPause gets a reference to the given bool and assigns it to the AutoPause field.
// Deprecated
func (o *ResumedSandbox) SetAutoPause(v bool) {
	o.AutoPause = &v
}

func (o ResumedSandbox) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResumedSandbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.AutoPause) {
		toSerialize["autoPause"] = o.AutoPause
	}
	return toSerialize, nil
}

type NullableResumedSandbox struct {
	value *ResumedSandbox
	isSet bool
}

func (v NullableResumedSandbox) Get() *ResumedSandbox {
	return v.value
}

func (v *NullableResumedSandbox) Set(val *ResumedSandbox) {
	v.value = val
	v.isSet = true
}

func (v NullableResumedSandbox) IsSet() bool {
	return v.isSet
}

func (v *NullableResumedSandbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResumedSandbox(val *ResumedSandbox) *NullableResumedSandbox {
	return &NullableResumedSandbox{value: val, isSet: true}
}

func (v NullableResumedSandbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResumedSandbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
