/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SandboxAutoResumeConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxAutoResumeConfig{}

// SandboxAutoResumeConfig Auto-resume configuration for paused sandboxes.
type SandboxAutoResumeConfig struct {
	// Auto-resume enabled flag for paused sandboxes. Default false.
	Enabled bool `json:"enabled"`
}

// NewSandboxAutoResumeConfig instantiates a new SandboxAutoResumeConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxAutoResumeConfig(enabled bool) *SandboxAutoResumeConfig {
	this := SandboxAutoResumeConfig{}
	this.Enabled = enabled
	return &this
}

// NewSandboxAutoResumeConfigWithDefaults instantiates a new SandboxAutoResumeConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxAutoResumeConfigWithDefaults() *SandboxAutoResumeConfig {
	this := SandboxAutoResumeConfig{}
	var enabled bool = false
	this.Enabled = enabled
	return &this
}

// GetEnabled returns the Enabled field value
func (o *SandboxAutoResumeConfig) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SandboxAutoResumeConfig) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SandboxAutoResumeConfig) SetEnabled(v bool) {
	o.Enabled = v
}

func (o SandboxAutoResumeConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxAutoResumeConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

type NullableSandboxAutoResumeConfig struct {
	value *SandboxAutoResumeConfig
	isSet bool
}

func (v NullableSandboxAutoResumeConfig) Get() *SandboxAutoResumeConfig {
	return v.value
}

func (v *NullableSandboxAutoResumeConfig) Set(val *SandboxAutoResumeConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxAutoResumeConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxAutoResumeConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxAutoResumeConfig(val *SandboxAutoResumeConfig) *NullableSandboxAutoResumeConfig {
	return &NullableSandboxAutoResumeConfig{value: val, isSet: true}
}

func (v NullableSandboxAutoResumeConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxAutoResumeConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
