/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the SandboxLog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxLog{}

// SandboxLog Log entry with timestamp and line
type SandboxLog struct {
	// Timestamp of the log entry
	Timestamp time.Time `json:"timestamp"`
	// Log line content
	Line string `json:"line"`
}

// NewSandboxLog instantiates a new SandboxLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxLog(timestamp time.Time, line string) *SandboxLog {
	this := SandboxLog{}
	this.Timestamp = timestamp
	this.Line = line
	return &this
}

// NewSandboxLogWithDefaults instantiates a new SandboxLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxLogWithDefaults() *SandboxLog {
	this := SandboxLog{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *SandboxLog) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *SandboxLog) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *SandboxLog) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetLine returns the Line field value
func (o *SandboxLog) GetLine() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Line
}

// GetLineOk returns a tuple with the Line field value
// and a boolean to check if the value has been set.
func (o *SandboxLog) GetLineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line, true
}

// SetLine sets field value
func (o *SandboxLog) SetLine(v string) {
	o.Line = v
}

func (o SandboxLog) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxLog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["line"] = o.Line
	return toSerialize, nil
}

type NullableSandboxLog struct {
	value *SandboxLog
	isSet bool
}

func (v NullableSandboxLog) Get() *SandboxLog {
	return v.value
}

func (v *NullableSandboxLog) Set(val *SandboxLog) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxLog) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxLog(val *SandboxLog) *NullableSandboxLog {
	return &NullableSandboxLog{value: val, isSet: true}
}

func (v NullableSandboxLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
