/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AssignedTemplateTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignedTemplateTags{}

// AssignedTemplateTags struct for AssignedTemplateTags
type AssignedTemplateTags struct {
	// Assigned tags of the template
	Tags []string `json:"tags"`
	// Identifier of the build associated with these tags
	BuildID string `json:"buildID"`
}

// NewAssignedTemplateTags instantiates a new AssignedTemplateTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignedTemplateTags(tags []string, buildID string) *AssignedTemplateTags {
	this := AssignedTemplateTags{}
	this.Tags = tags
	this.BuildID = buildID
	return &this
}

// NewAssignedTemplateTagsWithDefaults instantiates a new AssignedTemplateTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignedTemplateTagsWithDefaults() *AssignedTemplateTags {
	this := AssignedTemplateTags{}
	return &this
}

// GetTags returns the Tags field value
func (o *AssignedTemplateTags) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *AssignedTemplateTags) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *AssignedTemplateTags) SetTags(v []string) {
	o.Tags = v
}

// GetBuildID returns the BuildID field value
func (o *AssignedTemplateTags) GetBuildID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildID
}

// GetBuildIDOk returns a tuple with the BuildID field value
// and a boolean to check if the value has been set.
func (o *AssignedTemplateTags) GetBuildIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildID, true
}

// SetBuildID sets field value
func (o *AssignedTemplateTags) SetBuildID(v string) {
	o.BuildID = v
}

func (o AssignedTemplateTags) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignedTemplateTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tags"] = o.Tags
	toSerialize["buildID"] = o.BuildID
	return toSerialize, nil
}

type NullableAssignedTemplateTags struct {
	value *AssignedTemplateTags
	isSet bool
}

func (v NullableAssignedTemplateTags) Get() *AssignedTemplateTags {
	return v.value
}

func (v *NullableAssignedTemplateTags) Set(val *AssignedTemplateTags) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignedTemplateTags) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignedTemplateTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignedTemplateTags(val *AssignedTemplateTags) *NullableAssignedTemplateTags {
	return &NullableAssignedTemplateTags{value: val, isSet: true}
}

func (v NullableAssignedTemplateTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignedTemplateTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
