/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the ListedSandbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListedSandbox{}

// ListedSandbox struct for ListedSandbox
type ListedSandbox struct {
	// Identifier of the template from which is the sandbox created
	TemplateID string `json:"templateID"`
	// Alias of the template
	Alias *string `json:"alias,omitempty"`
	// Identifier of the sandbox
	SandboxID string `json:"sandboxID"`
	// Identifier of the api
	// Deprecated
	ClientID string `json:"clientID"`
	// Time when the sandbox was started
	StartedAt time.Time `json:"startedAt"`
	// Time when the sandbox will expire
	EndAt time.Time `json:"endAt"`
	// CPU cores for the sandbox
	CpuCount int32 `json:"cpuCount"`
	// Memory for the sandbox in MiB
	MemoryMB int32 `json:"memoryMB"`
	// Disk size for the sandbox in MiB
	DiskSizeMB int32              `json:"diskSizeMB"`
	Metadata   *map[string]string `json:"metadata,omitempty"`
	State      SandboxState       `json:"state"`
	// Version of the envd running in the sandbox
	EnvdVersion  string               `json:"envdVersion"`
	VolumeMounts []SandboxVolumeMount `json:"volumeMounts,omitempty"`
}

// NewListedSandbox instantiates a new ListedSandbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListedSandbox(templateID string, sandboxID string, clientID string, startedAt time.Time, endAt time.Time, cpuCount int32, memoryMB int32, diskSizeMB int32, state SandboxState, envdVersion string) *ListedSandbox {
	this := ListedSandbox{}
	this.TemplateID = templateID
	this.SandboxID = sandboxID
	this.ClientID = clientID
	this.StartedAt = startedAt
	this.EndAt = endAt
	this.CpuCount = cpuCount
	this.MemoryMB = memoryMB
	this.DiskSizeMB = diskSizeMB
	this.State = state
	this.EnvdVersion = envdVersion
	return &this
}

// NewListedSandboxWithDefaults instantiates a new ListedSandbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListedSandboxWithDefaults() *ListedSandbox {
	this := ListedSandbox{}
	return &this
}

// GetTemplateID returns the TemplateID field value
func (o *ListedSandbox) GetTemplateID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateID
}

// GetTemplateIDOk returns a tuple with the TemplateID field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetTemplateIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateID, true
}

// SetTemplateID sets field value
func (o *ListedSandbox) SetTemplateID(v string) {
	o.TemplateID = v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *ListedSandbox) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *ListedSandbox) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *ListedSandbox) SetAlias(v string) {
	o.Alias = &v
}

// GetSandboxID returns the SandboxID field value
func (o *ListedSandbox) GetSandboxID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SandboxID
}

// GetSandboxIDOk returns a tuple with the SandboxID field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetSandboxIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SandboxID, true
}

// SetSandboxID sets field value
func (o *ListedSandbox) SetSandboxID(v string) {
	o.SandboxID = v
}

// GetClientID returns the ClientID field value
// Deprecated
func (o *ListedSandbox) GetClientID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientID
}

// GetClientIDOk returns a tuple with the ClientID field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *ListedSandbox) GetClientIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientID, true
}

// SetClientID sets field value
// Deprecated
func (o *ListedSandbox) SetClientID(v string) {
	o.ClientID = v
}

// GetStartedAt returns the StartedAt field value
func (o *ListedSandbox) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *ListedSandbox) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetEndAt returns the EndAt field value
func (o *ListedSandbox) GetEndAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetEndAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndAt, true
}

// SetEndAt sets field value
func (o *ListedSandbox) SetEndAt(v time.Time) {
	o.EndAt = v
}

// GetCpuCount returns the CpuCount field value
func (o *ListedSandbox) GetCpuCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetCpuCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuCount, true
}

// SetCpuCount sets field value
func (o *ListedSandbox) SetCpuCount(v int32) {
	o.CpuCount = v
}

// GetMemoryMB returns the MemoryMB field value
func (o *ListedSandbox) GetMemoryMB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryMB
}

// GetMemoryMBOk returns a tuple with the MemoryMB field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetMemoryMBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryMB, true
}

// SetMemoryMB sets field value
func (o *ListedSandbox) SetMemoryMB(v int32) {
	o.MemoryMB = v
}

// GetDiskSizeMB returns the DiskSizeMB field value
func (o *ListedSandbox) GetDiskSizeMB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DiskSizeMB
}

// GetDiskSizeMBOk returns a tuple with the DiskSizeMB field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetDiskSizeMBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskSizeMB, true
}

// SetDiskSizeMB sets field value
func (o *ListedSandbox) SetDiskSizeMB(v int32) {
	o.DiskSizeMB = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ListedSandbox) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ListedSandbox) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *ListedSandbox) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetState returns the State field value
func (o *ListedSandbox) GetState() SandboxState {
	if o == nil {
		var ret SandboxState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetStateOk() (*SandboxState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ListedSandbox) SetState(v SandboxState) {
	o.State = v
}

// GetEnvdVersion returns the EnvdVersion field value
func (o *ListedSandbox) GetEnvdVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvdVersion
}

// GetEnvdVersionOk returns a tuple with the EnvdVersion field value
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetEnvdVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvdVersion, true
}

// SetEnvdVersion sets field value
func (o *ListedSandbox) SetEnvdVersion(v string) {
	o.EnvdVersion = v
}

// GetVolumeMounts returns the VolumeMounts field value if set, zero value otherwise.
func (o *ListedSandbox) GetVolumeMounts() []SandboxVolumeMount {
	if o == nil || IsNil(o.VolumeMounts) {
		var ret []SandboxVolumeMount
		return ret
	}
	return o.VolumeMounts
}

// GetVolumeMountsOk returns a tuple with the VolumeMounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListedSandbox) GetVolumeMountsOk() ([]SandboxVolumeMount, bool) {
	if o == nil || IsNil(o.VolumeMounts) {
		return nil, false
	}
	return o.VolumeMounts, true
}

// HasVolumeMounts returns a boolean if a field has been set.
func (o *ListedSandbox) HasVolumeMounts() bool {
	if o != nil && !IsNil(o.VolumeMounts) {
		return true
	}

	return false
}

// SetVolumeMounts gets a reference to the given []SandboxVolumeMount and assigns it to the VolumeMounts field.
func (o *ListedSandbox) SetVolumeMounts(v []SandboxVolumeMount) {
	o.VolumeMounts = v
}

func (o ListedSandbox) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListedSandbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["templateID"] = o.TemplateID
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	toSerialize["sandboxID"] = o.SandboxID
	toSerialize["clientID"] = o.ClientID
	toSerialize["startedAt"] = o.StartedAt
	toSerialize["endAt"] = o.EndAt
	toSerialize["cpuCount"] = o.CpuCount
	toSerialize["memoryMB"] = o.MemoryMB
	toSerialize["diskSizeMB"] = o.DiskSizeMB
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["state"] = o.State
	toSerialize["envdVersion"] = o.EnvdVersion
	if !IsNil(o.VolumeMounts) {
		toSerialize["volumeMounts"] = o.VolumeMounts
	}
	return toSerialize, nil
}

type NullableListedSandbox struct {
	value *ListedSandbox
	isSet bool
}

func (v NullableListedSandbox) Get() *ListedSandbox {
	return v.value
}

func (v *NullableListedSandbox) Set(val *ListedSandbox) {
	v.value = val
	v.isSet = true
}

func (v NullableListedSandbox) IsSet() bool {
	return v.isSet
}

func (v *NullableListedSandbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListedSandbox(val *ListedSandbox) *NullableListedSandbox {
	return &NullableListedSandbox{value: val, isSet: true}
}

func (v NullableListedSandbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListedSandbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
