/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the Node type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Node{}

// Node struct for Node
type Node struct {
	// Version of the orchestrator
	Version string `json:"version"`
	// Commit of the orchestrator
	Commit string `json:"commit"`
	// Identifier of the nomad node
	// Deprecated
	NodeID string `json:"nodeID"`
	// Identifier of the node
	Id string `json:"id"`
	// Service instance identifier of the node
	ServiceInstanceID string `json:"serviceInstanceID"`
	// Identifier of the cluster
	ClusterID   string      `json:"clusterID"`
	MachineInfo MachineInfo `json:"machineInfo"`
	Status      NodeStatus  `json:"status"`
	// Number of sandboxes running on the node
	SandboxCount int32       `json:"sandboxCount"`
	Metrics      NodeMetrics `json:"metrics"`
	// Number of sandbox create successes
	CreateSuccesses int32 `json:"createSuccesses"`
	// Number of sandbox create fails
	CreateFails int32 `json:"createFails"`
	// Number of starting Sandboxes
	SandboxStartingCount int32 `json:"sandboxStartingCount"`
}

// NewNode instantiates a new Node object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNode(version string, commit string, nodeID string, id string, serviceInstanceID string, clusterID string, machineInfo MachineInfo, status NodeStatus, sandboxCount int32, metrics NodeMetrics, createSuccesses int32, createFails int32, sandboxStartingCount int32) *Node {
	this := Node{}
	this.Version = version
	this.Commit = commit
	this.NodeID = nodeID
	this.Id = id
	this.ServiceInstanceID = serviceInstanceID
	this.ClusterID = clusterID
	this.MachineInfo = machineInfo
	this.Status = status
	this.SandboxCount = sandboxCount
	this.Metrics = metrics
	this.CreateSuccesses = createSuccesses
	this.CreateFails = createFails
	this.SandboxStartingCount = sandboxStartingCount
	return &this
}

// NewNodeWithDefaults instantiates a new Node object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeWithDefaults() *Node {
	this := Node{}
	return &this
}

// GetVersion returns the Version field value
func (o *Node) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *Node) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *Node) SetVersion(v string) {
	o.Version = v
}

// GetCommit returns the Commit field value
func (o *Node) GetCommit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Commit
}

// GetCommitOk returns a tuple with the Commit field value
// and a boolean to check if the value has been set.
func (o *Node) GetCommitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Commit, true
}

// SetCommit sets field value
func (o *Node) SetCommit(v string) {
	o.Commit = v
}

// GetNodeID returns the NodeID field value
// Deprecated
func (o *Node) GetNodeID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeID
}

// GetNodeIDOk returns a tuple with the NodeID field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *Node) GetNodeIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeID, true
}

// SetNodeID sets field value
// Deprecated
func (o *Node) SetNodeID(v string) {
	o.NodeID = v
}

// GetId returns the Id field value
func (o *Node) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Node) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Node) SetId(v string) {
	o.Id = v
}

// GetServiceInstanceID returns the ServiceInstanceID field value
func (o *Node) GetServiceInstanceID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceInstanceID
}

// GetServiceInstanceIDOk returns a tuple with the ServiceInstanceID field value
// and a boolean to check if the value has been set.
func (o *Node) GetServiceInstanceIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceInstanceID, true
}

// SetServiceInstanceID sets field value
func (o *Node) SetServiceInstanceID(v string) {
	o.ServiceInstanceID = v
}

// GetClusterID returns the ClusterID field value
func (o *Node) GetClusterID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClusterID
}

// GetClusterIDOk returns a tuple with the ClusterID field value
// and a boolean to check if the value has been set.
func (o *Node) GetClusterIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClusterID, true
}

// SetClusterID sets field value
func (o *Node) SetClusterID(v string) {
	o.ClusterID = v
}

// GetMachineInfo returns the MachineInfo field value
func (o *Node) GetMachineInfo() MachineInfo {
	if o == nil {
		var ret MachineInfo
		return ret
	}

	return o.MachineInfo
}

// GetMachineInfoOk returns a tuple with the MachineInfo field value
// and a boolean to check if the value has been set.
func (o *Node) GetMachineInfoOk() (*MachineInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MachineInfo, true
}

// SetMachineInfo sets field value
func (o *Node) SetMachineInfo(v MachineInfo) {
	o.MachineInfo = v
}

// GetStatus returns the Status field value
func (o *Node) GetStatus() NodeStatus {
	if o == nil {
		var ret NodeStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Node) GetStatusOk() (*NodeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Node) SetStatus(v NodeStatus) {
	o.Status = v
}

// GetSandboxCount returns the SandboxCount field value
func (o *Node) GetSandboxCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SandboxCount
}

// GetSandboxCountOk returns a tuple with the SandboxCount field value
// and a boolean to check if the value has been set.
func (o *Node) GetSandboxCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SandboxCount, true
}

// SetSandboxCount sets field value
func (o *Node) SetSandboxCount(v int32) {
	o.SandboxCount = v
}

// GetMetrics returns the Metrics field value
func (o *Node) GetMetrics() NodeMetrics {
	if o == nil {
		var ret NodeMetrics
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *Node) GetMetricsOk() (*NodeMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *Node) SetMetrics(v NodeMetrics) {
	o.Metrics = v
}

// GetCreateSuccesses returns the CreateSuccesses field value
func (o *Node) GetCreateSuccesses() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreateSuccesses
}

// GetCreateSuccessesOk returns a tuple with the CreateSuccesses field value
// and a boolean to check if the value has been set.
func (o *Node) GetCreateSuccessesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateSuccesses, true
}

// SetCreateSuccesses sets field value
func (o *Node) SetCreateSuccesses(v int32) {
	o.CreateSuccesses = v
}

// GetCreateFails returns the CreateFails field value
func (o *Node) GetCreateFails() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreateFails
}

// GetCreateFailsOk returns a tuple with the CreateFails field value
// and a boolean to check if the value has been set.
func (o *Node) GetCreateFailsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateFails, true
}

// SetCreateFails sets field value
func (o *Node) SetCreateFails(v int32) {
	o.CreateFails = v
}

// GetSandboxStartingCount returns the SandboxStartingCount field value
func (o *Node) GetSandboxStartingCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SandboxStartingCount
}

// GetSandboxStartingCountOk returns a tuple with the SandboxStartingCount field value
// and a boolean to check if the value has been set.
func (o *Node) GetSandboxStartingCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SandboxStartingCount, true
}

// SetSandboxStartingCount sets field value
func (o *Node) SetSandboxStartingCount(v int32) {
	o.SandboxStartingCount = v
}

func (o Node) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Node) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["commit"] = o.Commit
	toSerialize["nodeID"] = o.NodeID
	toSerialize["id"] = o.Id
	toSerialize["serviceInstanceID"] = o.ServiceInstanceID
	toSerialize["clusterID"] = o.ClusterID
	toSerialize["machineInfo"] = o.MachineInfo
	toSerialize["status"] = o.Status
	toSerialize["sandboxCount"] = o.SandboxCount
	toSerialize["metrics"] = o.Metrics
	toSerialize["createSuccesses"] = o.CreateSuccesses
	toSerialize["createFails"] = o.CreateFails
	toSerialize["sandboxStartingCount"] = o.SandboxStartingCount
	return toSerialize, nil
}

type NullableNode struct {
	value *Node
	isSet bool
}

func (v NullableNode) Get() *Node {
	return v.value
}

func (v *NullableNode) Set(val *Node) {
	v.value = val
	v.isSet = true
}

func (v NullableNode) IsSet() bool {
	return v.isSet
}

func (v *NullableNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNode(val *Node) *NullableNode {
	return &NullableNode{value: val, isSet: true}
}

func (v NullableNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
