/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// LogsSource Source of the logs that should be returned
type LogsSource string

// List of LogsSource
const (
	LOGSSOURCE_LogsSourceTemporary  LogsSource = "temporary"
	LOGSSOURCE_LogsSourcePersistent LogsSource = "persistent"
)

// All allowed values of LogsSource enum
var AllowedLogsSourceEnumValues = []LogsSource{
	"temporary",
	"persistent",
}

func (v *LogsSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LogsSource(value)
	for _, existing := range AllowedLogsSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LogsSource", value)
}

// NewLogsSourceFromValue returns a pointer to a valid LogsSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLogsSourceFromValue(v string) (*LogsSource, error) {
	ev := LogsSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LogsSource: valid values are %v", v, AllowedLogsSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LogsSource) IsValid() bool {
	for _, existing := range AllowedLogsSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LogsSource value
func (v LogsSource) Ptr() *LogsSource {
	return &v
}

type NullableLogsSource struct {
	value *LogsSource
	isSet bool
}

func (v NullableLogsSource) Get() *LogsSource {
	return v.value
}

func (v *NullableLogsSource) Set(val *LogsSource) {
	v.value = val
	v.isSet = true
}

func (v NullableLogsSource) IsSet() bool {
	return v.isSet
}

func (v *NullableLogsSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogsSource(val *LogsSource) *NullableLogsSource {
	return &NullableLogsSource{value: val, isSet: true}
}

func (v NullableLogsSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogsSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
