/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the MaxTeamMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaxTeamMetric{}

// MaxTeamMetric Team metric with timestamp
type MaxTeamMetric struct {
	// Timestamp of the metric entry
	// Deprecated
	Timestamp time.Time `json:"timestamp"`
	// Timestamp of the metric entry in Unix time (seconds since epoch)
	TimestampUnix int64 `json:"timestampUnix"`
	// The maximum value of the requested metric in the given interval
	Value float32 `json:"value"`
}

// NewMaxTeamMetric instantiates a new MaxTeamMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaxTeamMetric(timestamp time.Time, timestampUnix int64, value float32) *MaxTeamMetric {
	this := MaxTeamMetric{}
	this.Timestamp = timestamp
	this.TimestampUnix = timestampUnix
	this.Value = value
	return &this
}

// NewMaxTeamMetricWithDefaults instantiates a new MaxTeamMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaxTeamMetricWithDefaults() *MaxTeamMetric {
	this := MaxTeamMetric{}
	return &this
}

// GetTimestamp returns the Timestamp field value
// Deprecated
func (o *MaxTeamMetric) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *MaxTeamMetric) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
// Deprecated
func (o *MaxTeamMetric) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetTimestampUnix returns the TimestampUnix field value
func (o *MaxTeamMetric) GetTimestampUnix() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TimestampUnix
}

// GetTimestampUnixOk returns a tuple with the TimestampUnix field value
// and a boolean to check if the value has been set.
func (o *MaxTeamMetric) GetTimestampUnixOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimestampUnix, true
}

// SetTimestampUnix sets field value
func (o *MaxTeamMetric) SetTimestampUnix(v int64) {
	o.TimestampUnix = v
}

// GetValue returns the Value field value
func (o *MaxTeamMetric) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *MaxTeamMetric) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *MaxTeamMetric) SetValue(v float32) {
	o.Value = v
}

func (o MaxTeamMetric) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaxTeamMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["timestampUnix"] = o.TimestampUnix
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableMaxTeamMetric struct {
	value *MaxTeamMetric
	isSet bool
}

func (v NullableMaxTeamMetric) Get() *MaxTeamMetric {
	return v.value
}

func (v *NullableMaxTeamMetric) Set(val *MaxTeamMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableMaxTeamMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableMaxTeamMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaxTeamMetric(val *MaxTeamMetric) *NullableMaxTeamMetric {
	return &NullableMaxTeamMetric{value: val, isSet: true}
}

func (v NullableMaxTeamMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaxTeamMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
