/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the TemplateLegacy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateLegacy{}

// TemplateLegacy struct for TemplateLegacy
type TemplateLegacy struct {
	// Identifier of the template
	TemplateID string `json:"templateID"`
	// Identifier of the last successful build for given template
	BuildID string `json:"buildID"`
	// CPU cores for the sandbox
	CpuCount int32 `json:"cpuCount"`
	// Memory for the sandbox in MiB
	MemoryMB int32 `json:"memoryMB"`
	// Disk size for the sandbox in MiB
	DiskSizeMB int32 `json:"diskSizeMB"`
	// Whether the template is public or only accessible by the team
	Public bool `json:"public"`
	// Aliases of the template
	Aliases []string `json:"aliases"`
	// Time when the template was created
	CreatedAt time.Time `json:"createdAt"`
	// Time when the template was last updated
	UpdatedAt time.Time        `json:"updatedAt"`
	CreatedBy NullableTeamUser `json:"createdBy"`
	// Time when the template was last used
	LastSpawnedAt NullableTime `json:"lastSpawnedAt"`
	// Number of times the template was used
	SpawnCount int64 `json:"spawnCount"`
	// Number of times the template was built
	BuildCount int32 `json:"buildCount"`
	// Version of the envd running in the sandbox
	EnvdVersion string `json:"envdVersion"`
}

// NewTemplateLegacy instantiates a new TemplateLegacy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateLegacy(templateID string, buildID string, cpuCount int32, memoryMB int32, diskSizeMB int32, public bool, aliases []string, createdAt time.Time, updatedAt time.Time, createdBy NullableTeamUser, lastSpawnedAt NullableTime, spawnCount int64, buildCount int32, envdVersion string) *TemplateLegacy {
	this := TemplateLegacy{}
	this.TemplateID = templateID
	this.BuildID = buildID
	this.CpuCount = cpuCount
	this.MemoryMB = memoryMB
	this.DiskSizeMB = diskSizeMB
	this.Public = public
	this.Aliases = aliases
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.CreatedBy = createdBy
	this.LastSpawnedAt = lastSpawnedAt
	this.SpawnCount = spawnCount
	this.BuildCount = buildCount
	this.EnvdVersion = envdVersion
	return &this
}

// NewTemplateLegacyWithDefaults instantiates a new TemplateLegacy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateLegacyWithDefaults() *TemplateLegacy {
	this := TemplateLegacy{}
	return &this
}

// GetTemplateID returns the TemplateID field value
func (o *TemplateLegacy) GetTemplateID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateID
}

// GetTemplateIDOk returns a tuple with the TemplateID field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetTemplateIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateID, true
}

// SetTemplateID sets field value
func (o *TemplateLegacy) SetTemplateID(v string) {
	o.TemplateID = v
}

// GetBuildID returns the BuildID field value
func (o *TemplateLegacy) GetBuildID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildID
}

// GetBuildIDOk returns a tuple with the BuildID field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetBuildIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildID, true
}

// SetBuildID sets field value
func (o *TemplateLegacy) SetBuildID(v string) {
	o.BuildID = v
}

// GetCpuCount returns the CpuCount field value
func (o *TemplateLegacy) GetCpuCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetCpuCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuCount, true
}

// SetCpuCount sets field value
func (o *TemplateLegacy) SetCpuCount(v int32) {
	o.CpuCount = v
}

// GetMemoryMB returns the MemoryMB field value
func (o *TemplateLegacy) GetMemoryMB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryMB
}

// GetMemoryMBOk returns a tuple with the MemoryMB field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetMemoryMBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryMB, true
}

// SetMemoryMB sets field value
func (o *TemplateLegacy) SetMemoryMB(v int32) {
	o.MemoryMB = v
}

// GetDiskSizeMB returns the DiskSizeMB field value
func (o *TemplateLegacy) GetDiskSizeMB() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DiskSizeMB
}

// GetDiskSizeMBOk returns a tuple with the DiskSizeMB field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetDiskSizeMBOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskSizeMB, true
}

// SetDiskSizeMB sets field value
func (o *TemplateLegacy) SetDiskSizeMB(v int32) {
	o.DiskSizeMB = v
}

// GetPublic returns the Public field value
func (o *TemplateLegacy) GetPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Public
}

// GetPublicOk returns a tuple with the Public field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Public, true
}

// SetPublic sets field value
func (o *TemplateLegacy) SetPublic(v bool) {
	o.Public = v
}

// GetAliases returns the Aliases field value
func (o *TemplateLegacy) GetAliases() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetAliasesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aliases, true
}

// SetAliases sets field value
func (o *TemplateLegacy) SetAliases(v []string) {
	o.Aliases = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TemplateLegacy) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TemplateLegacy) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TemplateLegacy) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TemplateLegacy) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
// If the value is explicit nil, the zero value for TeamUser will be returned
func (o *TemplateLegacy) GetCreatedBy() TeamUser {
	if o == nil || o.CreatedBy.Get() == nil {
		var ret TeamUser
		return ret
	}

	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateLegacy) GetCreatedByOk() (*TeamUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// SetCreatedBy sets field value
func (o *TemplateLegacy) SetCreatedBy(v TeamUser) {
	o.CreatedBy.Set(&v)
}

// GetLastSpawnedAt returns the LastSpawnedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TemplateLegacy) GetLastSpawnedAt() time.Time {
	if o == nil || o.LastSpawnedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastSpawnedAt.Get()
}

// GetLastSpawnedAtOk returns a tuple with the LastSpawnedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateLegacy) GetLastSpawnedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastSpawnedAt.Get(), o.LastSpawnedAt.IsSet()
}

// SetLastSpawnedAt sets field value
func (o *TemplateLegacy) SetLastSpawnedAt(v time.Time) {
	o.LastSpawnedAt.Set(&v)
}

// GetSpawnCount returns the SpawnCount field value
func (o *TemplateLegacy) GetSpawnCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SpawnCount
}

// GetSpawnCountOk returns a tuple with the SpawnCount field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetSpawnCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpawnCount, true
}

// SetSpawnCount sets field value
func (o *TemplateLegacy) SetSpawnCount(v int64) {
	o.SpawnCount = v
}

// GetBuildCount returns the BuildCount field value
func (o *TemplateLegacy) GetBuildCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BuildCount
}

// GetBuildCountOk returns a tuple with the BuildCount field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetBuildCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildCount, true
}

// SetBuildCount sets field value
func (o *TemplateLegacy) SetBuildCount(v int32) {
	o.BuildCount = v
}

// GetEnvdVersion returns the EnvdVersion field value
func (o *TemplateLegacy) GetEnvdVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvdVersion
}

// GetEnvdVersionOk returns a tuple with the EnvdVersion field value
// and a boolean to check if the value has been set.
func (o *TemplateLegacy) GetEnvdVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvdVersion, true
}

// SetEnvdVersion sets field value
func (o *TemplateLegacy) SetEnvdVersion(v string) {
	o.EnvdVersion = v
}

func (o TemplateLegacy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateLegacy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["templateID"] = o.TemplateID
	toSerialize["buildID"] = o.BuildID
	toSerialize["cpuCount"] = o.CpuCount
	toSerialize["memoryMB"] = o.MemoryMB
	toSerialize["diskSizeMB"] = o.DiskSizeMB
	toSerialize["public"] = o.Public
	toSerialize["aliases"] = o.Aliases
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["createdBy"] = o.CreatedBy.Get()
	toSerialize["lastSpawnedAt"] = o.LastSpawnedAt.Get()
	toSerialize["spawnCount"] = o.SpawnCount
	toSerialize["buildCount"] = o.BuildCount
	toSerialize["envdVersion"] = o.EnvdVersion
	return toSerialize, nil
}

type NullableTemplateLegacy struct {
	value *TemplateLegacy
	isSet bool
}

func (v NullableTemplateLegacy) Get() *TemplateLegacy {
	return v.value
}

func (v *NullableTemplateLegacy) Set(val *TemplateLegacy) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateLegacy) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateLegacy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateLegacy(val *TemplateLegacy) *NullableTemplateLegacy {
	return &NullableTemplateLegacy{value: val, isSet: true}
}

func (v NullableTemplateLegacy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateLegacy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
