/*
E2B API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TemplateBuildInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateBuildInfo{}

// TemplateBuildInfo struct for TemplateBuildInfo
type TemplateBuildInfo struct {
	// Build logs
	Logs []string `json:"logs"`
	// Build logs structured
	LogEntries []BuildLogEntry `json:"logEntries"`
	// Identifier of the template
	TemplateID string `json:"templateID"`
	// Identifier of the build
	BuildID string              `json:"buildID"`
	Status  TemplateBuildStatus `json:"status"`
	Reason  *BuildStatusReason  `json:"reason,omitempty"`
}

// NewTemplateBuildInfo instantiates a new TemplateBuildInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateBuildInfo(logs []string, logEntries []BuildLogEntry, templateID string, buildID string, status TemplateBuildStatus) *TemplateBuildInfo {
	this := TemplateBuildInfo{}
	this.Logs = logs
	this.LogEntries = logEntries
	this.TemplateID = templateID
	this.BuildID = buildID
	this.Status = status
	return &this
}

// NewTemplateBuildInfoWithDefaults instantiates a new TemplateBuildInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateBuildInfoWithDefaults() *TemplateBuildInfo {
	this := TemplateBuildInfo{}
	return &this
}

// GetLogs returns the Logs field value
func (o *TemplateBuildInfo) GetLogs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *TemplateBuildInfo) GetLogsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs, true
}

// SetLogs sets field value
func (o *TemplateBuildInfo) SetLogs(v []string) {
	o.Logs = v
}

// GetLogEntries returns the LogEntries field value
func (o *TemplateBuildInfo) GetLogEntries() []BuildLogEntry {
	if o == nil {
		var ret []BuildLogEntry
		return ret
	}

	return o.LogEntries
}

// GetLogEntriesOk returns a tuple with the LogEntries field value
// and a boolean to check if the value has been set.
func (o *TemplateBuildInfo) GetLogEntriesOk() ([]BuildLogEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogEntries, true
}

// SetLogEntries sets field value
func (o *TemplateBuildInfo) SetLogEntries(v []BuildLogEntry) {
	o.LogEntries = v
}

// GetTemplateID returns the TemplateID field value
func (o *TemplateBuildInfo) GetTemplateID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateID
}

// GetTemplateIDOk returns a tuple with the TemplateID field value
// and a boolean to check if the value has been set.
func (o *TemplateBuildInfo) GetTemplateIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateID, true
}

// SetTemplateID sets field value
func (o *TemplateBuildInfo) SetTemplateID(v string) {
	o.TemplateID = v
}

// GetBuildID returns the BuildID field value
func (o *TemplateBuildInfo) GetBuildID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildID
}

// GetBuildIDOk returns a tuple with the BuildID field value
// and a boolean to check if the value has been set.
func (o *TemplateBuildInfo) GetBuildIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildID, true
}

// SetBuildID sets field value
func (o *TemplateBuildInfo) SetBuildID(v string) {
	o.BuildID = v
}

// GetStatus returns the Status field value
func (o *TemplateBuildInfo) GetStatus() TemplateBuildStatus {
	if o == nil {
		var ret TemplateBuildStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TemplateBuildInfo) GetStatusOk() (*TemplateBuildStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TemplateBuildInfo) SetStatus(v TemplateBuildStatus) {
	o.Status = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *TemplateBuildInfo) GetReason() BuildStatusReason {
	if o == nil || IsNil(o.Reason) {
		var ret BuildStatusReason
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateBuildInfo) GetReasonOk() (*BuildStatusReason, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *TemplateBuildInfo) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given BuildStatusReason and assigns it to the Reason field.
func (o *TemplateBuildInfo) SetReason(v BuildStatusReason) {
	o.Reason = &v
}

func (o TemplateBuildInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateBuildInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logs"] = o.Logs
	toSerialize["logEntries"] = o.LogEntries
	toSerialize["templateID"] = o.TemplateID
	toSerialize["buildID"] = o.BuildID
	toSerialize["status"] = o.Status
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableTemplateBuildInfo struct {
	value *TemplateBuildInfo
	isSet bool
}

func (v NullableTemplateBuildInfo) Get() *TemplateBuildInfo {
	return v.value
}

func (v *NullableTemplateBuildInfo) Set(val *TemplateBuildInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateBuildInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateBuildInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateBuildInfo(val *TemplateBuildInfo) *NullableTemplateBuildInfo {
	return &NullableTemplateBuildInfo{value: val, isSet: true}
}

func (v NullableTemplateBuildInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateBuildInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
