/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	agentsapiagentsv1alpha1 "github.com/openkruise/agents-api/agents/v1alpha1"
	versioned "github.com/openkruise/agents-api/client/clientset/versioned"
	internalinterfaces "github.com/openkruise/agents-api/client/informers/externalversions/internalinterfaces"
	agentsv1alpha1 "github.com/openkruise/agents-api/client/listers/agents/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SecurityProfileInformer provides access to a shared informer and lister for
// SecurityProfiles.
type SecurityProfileInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() agentsv1alpha1.SecurityProfileLister
}

type securityProfileInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecurityProfileInformer constructs a new informer for SecurityProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecurityProfileInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecurityProfileInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecurityProfileInformer constructs a new informer for SecurityProfile type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecurityProfileInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().SecurityProfiles(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().SecurityProfiles(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().SecurityProfiles(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AgentsV1alpha1().SecurityProfiles(namespace).Watch(ctx, options)
			},
		}, client),
		&agentsapiagentsv1alpha1.SecurityProfile{},
		resyncPeriod,
		indexers,
	)
}

func (f *securityProfileInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecurityProfileInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *securityProfileInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&agentsapiagentsv1alpha1.SecurityProfile{}, f.defaultInformer)
}

func (f *securityProfileInformer) Lister() agentsv1alpha1.SecurityProfileLister {
	return agentsv1alpha1.NewSecurityProfileLister(f.Informer().GetIndexer())
}
