// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filesystem/filesystem.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.filesystem;

@com.google.protobuf.Generated
public final class FilesystemProto extends com.google.protobuf.GeneratedFile {
  private FilesystemProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "FilesystemProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_MoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_MoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MakeDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_MakeDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_MakeDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_MakeDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_RemoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_RemoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_RemoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_RemoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_StatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_StatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_StatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_StatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_EntryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_EntryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ListDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_ListDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_ListDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_ListDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_WatchDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_WatchDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_FilesystemEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_FilesystemEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_WatchDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_WatchDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_WatchDirResponse_StartEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_WatchDirResponse_StartEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_WatchDirResponse_KeepAlive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_WatchDirResponse_KeepAlive_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_CreateWatcherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_CreateWatcherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_CreateWatcherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_CreateWatcherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_GetWatcherEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_GetWatcherEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_GetWatcherEventsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_GetWatcherEventsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_RemoveWatcherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_RemoveWatcherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_filesystem_RemoveWatcherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filesystem_RemoveWatcherResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033filesystem/filesystem.proto\022\nfilesyste" +
      "m\032\037google/protobuf/timestamp.proto\"G\n\013Mo" +
      "veRequest\022\026\n\006source\030\001 \001(\tR\006source\022 \n\013des" +
      "tination\030\002 \001(\tR\013destination\";\n\014MoveRespo" +
      "nse\022+\n\005entry\030\001 \001(\0132\025.filesystem.EntryInf" +
      "oR\005entry\"$\n\016MakeDirRequest\022\022\n\004path\030\001 \001(\t" +
      "R\004path\">\n\017MakeDirResponse\022+\n\005entry\030\001 \001(\013" +
      "2\025.filesystem.EntryInfoR\005entry\"#\n\rRemove" +
      "Request\022\022\n\004path\030\001 \001(\tR\004path\"\020\n\016RemoveRes" +
      "ponse\"!\n\013StatRequest\022\022\n\004path\030\001 \001(\tR\004path" +
      "\";\n\014StatResponse\022+\n\005entry\030\001 \001(\0132\025.filesy" +
      "stem.EntryInfoR\005entry\"\323\002\n\tEntryInfo\022\022\n\004n" +
      "ame\030\001 \001(\tR\004name\022(\n\004type\030\002 \001(\0162\024.filesyst" +
      "em.FileTypeR\004type\022\022\n\004path\030\003 \001(\tR\004path\022\022\n" +
      "\004size\030\004 \001(\003R\004size\022\022\n\004mode\030\005 \001(\rR\004mode\022 \n" +
      "\013permissions\030\006 \001(\tR\013permissions\022\024\n\005owner" +
      "\030\007 \001(\tR\005owner\022\024\n\005group\030\010 \001(\tR\005group\022?\n\rm" +
      "odified_time\030\t \001(\0132\032.google.protobuf.Tim" +
      "estampR\014modifiedTime\022*\n\016symlink_target\030\n" +
      " \001(\tH\000R\rsymlinkTarget\210\001\001B\021\n\017_symlink_tar" +
      "get\":\n\016ListDirRequest\022\022\n\004path\030\001 \001(\tR\004pat" +
      "h\022\024\n\005depth\030\002 \001(\rR\005depth\"B\n\017ListDirRespon" +
      "se\022/\n\007entries\030\001 \003(\0132\025.filesystem.EntryIn" +
      "foR\007entries\"C\n\017WatchDirRequest\022\022\n\004path\030\001" +
      " \001(\tR\004path\022\034\n\trecursive\030\002 \001(\010R\trecursive" +
      "\"P\n\017FilesystemEvent\022\022\n\004name\030\001 \001(\tR\004name\022" +
      ")\n\004type\030\002 \001(\0162\025.filesystem.EventTypeR\004ty" +
      "pe\"\376\001\n\020WatchDirResponse\022?\n\005start\030\001 \001(\0132\'" +
      ".filesystem.WatchDirResponse.StartEventH" +
      "\000R\005start\022=\n\nfilesystem\030\002 \001(\0132\033.filesyste" +
      "m.FilesystemEventH\000R\nfilesystem\022F\n\tkeepa" +
      "live\030\003 \001(\0132&.filesystem.WatchDirResponse" +
      ".KeepAliveH\000R\tkeepalive\032\014\n\nStartEvent\032\013\n" +
      "\tKeepAliveB\007\n\005event\"H\n\024CreateWatcherRequ" +
      "est\022\022\n\004path\030\001 \001(\tR\004path\022\034\n\trecursive\030\002 \001" +
      "(\010R\trecursive\"6\n\025CreateWatcherResponse\022\035" +
      "\n\nwatcher_id\030\001 \001(\tR\twatcherId\"8\n\027GetWatc" +
      "herEventsRequest\022\035\n\nwatcher_id\030\001 \001(\tR\twa" +
      "tcherId\"O\n\030GetWatcherEventsResponse\0223\n\006e" +
      "vents\030\001 \003(\0132\033.filesystem.FilesystemEvent" +
      "R\006events\"5\n\024RemoveWatcherRequest\022\035\n\nwatc" +
      "her_id\030\001 \001(\tR\twatcherId\"\027\n\025RemoveWatcher" +
      "Response*i\n\010FileType\022\031\n\025FILE_TYPE_UNSPEC" +
      "IFIED\020\000\022\022\n\016FILE_TYPE_FILE\020\001\022\027\n\023FILE_TYPE" +
      "_DIRECTORY\020\002\022\025\n\021FILE_TYPE_SYMLINK\020\003*\230\001\n\t" +
      "EventType\022\032\n\026EVENT_TYPE_UNSPECIFIED\020\000\022\025\n" +
      "\021EVENT_TYPE_CREATE\020\001\022\024\n\020EVENT_TYPE_WRITE" +
      "\020\002\022\025\n\021EVENT_TYPE_REMOVE\020\003\022\025\n\021EVENT_TYPE_" +
      "RENAME\020\004\022\024\n\020EVENT_TYPE_CHMOD\020\0052\237\005\n\nFiles" +
      "ystem\0229\n\004Stat\022\027.filesystem.StatRequest\032\030" +
      ".filesystem.StatResponse\022B\n\007MakeDir\022\032.fi" +
      "lesystem.MakeDirRequest\032\033.filesystem.Mak" +
      "eDirResponse\0229\n\004Move\022\027.filesystem.MoveRe" +
      "quest\032\030.filesystem.MoveResponse\022B\n\007ListD" +
      "ir\022\032.filesystem.ListDirRequest\032\033.filesys" +
      "tem.ListDirResponse\022?\n\006Remove\022\031.filesyst" +
      "em.RemoveRequest\032\032.filesystem.RemoveResp" +
      "onse\022G\n\010WatchDir\022\033.filesystem.WatchDirRe" +
      "quest\032\034.filesystem.WatchDirResponse0\001\022T\n" +
      "\rCreateWatcher\022 .filesystem.CreateWatche" +
      "rRequest\032!.filesystem.CreateWatcherRespo" +
      "nse\022]\n\020GetWatcherEvents\022#.filesystem.Get" +
      "WatcherEventsRequest\032$.filesystem.GetWat" +
      "cherEventsResponse\022T\n\rRemoveWatcher\022 .fi" +
      "lesystem.RemoveWatcherRequest\032!.filesyst" +
      "em.RemoveWatcherResponseB\212\001\n/io.openkrui" +
      "se.agents.client.e2b.envd.filesystemB\017Fi" +
      "lesystemProtoP\001\242\002\003FXX\252\002\nFilesystem\312\002\nFil" +
      "esystem\342\002\026Filesystem\\GPBMetadata\352\002\nFiles" +
      "ystemb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_filesystem_MoveRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_filesystem_MoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_MoveRequest_descriptor,
        new String[] { "Source", "Destination", });
    internal_static_filesystem_MoveResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_filesystem_MoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_MoveResponse_descriptor,
        new String[] { "Entry", });
    internal_static_filesystem_MakeDirRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_filesystem_MakeDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_MakeDirRequest_descriptor,
        new String[] { "Path", });
    internal_static_filesystem_MakeDirResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_filesystem_MakeDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_MakeDirResponse_descriptor,
        new String[] { "Entry", });
    internal_static_filesystem_RemoveRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_filesystem_RemoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_RemoveRequest_descriptor,
        new String[] { "Path", });
    internal_static_filesystem_RemoveResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_filesystem_RemoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_RemoveResponse_descriptor,
        new String[] { });
    internal_static_filesystem_StatRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_filesystem_StatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_StatRequest_descriptor,
        new String[] { "Path", });
    internal_static_filesystem_StatResponse_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_filesystem_StatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_StatResponse_descriptor,
        new String[] { "Entry", });
    internal_static_filesystem_EntryInfo_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_filesystem_EntryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_EntryInfo_descriptor,
        new String[] { "Name", "Type", "Path", "Size", "Mode", "Permissions", "Owner", "Group", "ModifiedTime", "SymlinkTarget", });
    internal_static_filesystem_ListDirRequest_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_filesystem_ListDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_ListDirRequest_descriptor,
        new String[] { "Path", "Depth", });
    internal_static_filesystem_ListDirResponse_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_filesystem_ListDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_ListDirResponse_descriptor,
        new String[] { "Entries", });
    internal_static_filesystem_WatchDirRequest_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_filesystem_WatchDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_WatchDirRequest_descriptor,
        new String[] { "Path", "Recursive", });
    internal_static_filesystem_FilesystemEvent_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_filesystem_FilesystemEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_FilesystemEvent_descriptor,
        new String[] { "Name", "Type", });
    internal_static_filesystem_WatchDirResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_filesystem_WatchDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_WatchDirResponse_descriptor,
        new String[] { "Start", "Filesystem", "Keepalive", "Event", });
    internal_static_filesystem_WatchDirResponse_StartEvent_descriptor =
      internal_static_filesystem_WatchDirResponse_descriptor.getNestedType(0);
    internal_static_filesystem_WatchDirResponse_StartEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_WatchDirResponse_StartEvent_descriptor,
        new String[] { });
    internal_static_filesystem_WatchDirResponse_KeepAlive_descriptor =
      internal_static_filesystem_WatchDirResponse_descriptor.getNestedType(1);
    internal_static_filesystem_WatchDirResponse_KeepAlive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_WatchDirResponse_KeepAlive_descriptor,
        new String[] { });
    internal_static_filesystem_CreateWatcherRequest_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_filesystem_CreateWatcherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_CreateWatcherRequest_descriptor,
        new String[] { "Path", "Recursive", });
    internal_static_filesystem_CreateWatcherResponse_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_filesystem_CreateWatcherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_CreateWatcherResponse_descriptor,
        new String[] { "WatcherId", });
    internal_static_filesystem_GetWatcherEventsRequest_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_filesystem_GetWatcherEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_GetWatcherEventsRequest_descriptor,
        new String[] { "WatcherId", });
    internal_static_filesystem_GetWatcherEventsResponse_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_filesystem_GetWatcherEventsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_GetWatcherEventsResponse_descriptor,
        new String[] { "Events", });
    internal_static_filesystem_RemoveWatcherRequest_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_filesystem_RemoveWatcherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_RemoveWatcherRequest_descriptor,
        new String[] { "WatcherId", });
    internal_static_filesystem_RemoveWatcherResponse_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_filesystem_RemoveWatcherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_filesystem_RemoveWatcherResponse_descriptor,
        new String[] { });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
