// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filesystem/filesystem.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.filesystem;

@com.google.protobuf.Generated
public interface MoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.MoveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1 [json_name = "source"];</code>
   * @return The source.
   */
  String getSource();
  /**
   * <code>string source = 1 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string destination = 2 [json_name = "destination"];</code>
   * @return The destination.
   */
  String getDestination();
  /**
   * <code>string destination = 2 [json_name = "destination"];</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
