/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	agentsv1alpha1 "github.com/openkruise/agents-api/agents/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GlobalSecurityProfileLister helps list GlobalSecurityProfiles.
// All objects returned here must be treated as read-only.
type GlobalSecurityProfileLister interface {
	// List lists all GlobalSecurityProfiles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsv1alpha1.GlobalSecurityProfile, err error)
	// Get retrieves the GlobalSecurityProfile from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agentsv1alpha1.GlobalSecurityProfile, error)
	GlobalSecurityProfileListerExpansion
}

// globalSecurityProfileLister implements the GlobalSecurityProfileLister interface.
type globalSecurityProfileLister struct {
	listers.ResourceIndexer[*agentsv1alpha1.GlobalSecurityProfile]
}

// NewGlobalSecurityProfileLister returns a new GlobalSecurityProfileLister.
func NewGlobalSecurityProfileLister(indexer cache.Indexer) GlobalSecurityProfileLister {
	return &globalSecurityProfileLister{listers.New[*agentsv1alpha1.GlobalSecurityProfile](indexer, agentsv1alpha1.Resource("globalsecurityprofile"))}
}
