/*
Copyright 2025 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	agentsv1alpha1 "github.com/openkruise/agents-api/agents/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SandboxUpdateOpsLister helps list SandboxUpdateOps.
// All objects returned here must be treated as read-only.
type SandboxUpdateOpsLister interface {
	// List lists all SandboxUpdateOps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsv1alpha1.SandboxUpdateOps, err error)
	// SandboxUpdateOps returns an object that can list and get SandboxUpdateOps.
	SandboxUpdateOps(namespace string) SandboxUpdateOpsNamespaceLister
	SandboxUpdateOpsListerExpansion
}

// sandboxUpdateOpsLister implements the SandboxUpdateOpsLister interface.
type sandboxUpdateOpsLister struct {
	listers.ResourceIndexer[*agentsv1alpha1.SandboxUpdateOps]
}

// NewSandboxUpdateOpsLister returns a new SandboxUpdateOpsLister.
func NewSandboxUpdateOpsLister(indexer cache.Indexer) SandboxUpdateOpsLister {
	return &sandboxUpdateOpsLister{listers.New[*agentsv1alpha1.SandboxUpdateOps](indexer, agentsv1alpha1.Resource("sandboxupdateops"))}
}

// SandboxUpdateOps returns an object that can list and get SandboxUpdateOps.
func (s *sandboxUpdateOpsLister) SandboxUpdateOps(namespace string) SandboxUpdateOpsNamespaceLister {
	return sandboxUpdateOpsNamespaceLister{listers.NewNamespaced[*agentsv1alpha1.SandboxUpdateOps](s.ResourceIndexer, namespace)}
}

// SandboxUpdateOpsNamespaceLister helps list and get SandboxUpdateOps.
// All objects returned here must be treated as read-only.
type SandboxUpdateOpsNamespaceLister interface {
	// List lists all SandboxUpdateOps in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentsv1alpha1.SandboxUpdateOps, err error)
	// Get retrieves the SandboxUpdateOps from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agentsv1alpha1.SandboxUpdateOps, error)
	SandboxUpdateOpsNamespaceListerExpansion
}

// sandboxUpdateOpsNamespaceLister implements the SandboxUpdateOpsNamespaceLister
// interface.
type sandboxUpdateOpsNamespaceLister struct {
	listers.ResourceIndexer[*agentsv1alpha1.SandboxUpdateOps]
}
