// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filesystem/filesystem.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.filesystem;

@com.google.protobuf.Generated
public interface GetWatcherEventsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.GetWatcherEventsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .filesystem.FilesystemEvent events = 1 [json_name = "events"];</code>
   */
  java.util.List<FilesystemEvent>
      getEventsList();
  /**
   * <code>repeated .filesystem.FilesystemEvent events = 1 [json_name = "events"];</code>
   */
  FilesystemEvent getEvents(int index);
  /**
   * <code>repeated .filesystem.FilesystemEvent events = 1 [json_name = "events"];</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .filesystem.FilesystemEvent events = 1 [json_name = "events"];</code>
   */
  java.util.List<? extends FilesystemEventOrBuilder>
      getEventsOrBuilderList();
  /**
   * <code>repeated .filesystem.FilesystemEvent events = 1 [json_name = "events"];</code>
   */
  FilesystemEventOrBuilder getEventsOrBuilder(
      int index);
}
