// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filesystem/filesystem.proto
// Protobuf Java Version: 4.34.0

package io.openkruise.agents.client.runtime.envd.filesystem;

@com.google.protobuf.Generated
public interface MakeDirResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:filesystem.MakeDirResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
   * @return Whether the entry field is set.
   */
  boolean hasEntry();
  /**
   * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
   * @return The entry.
   */
  EntryInfo getEntry();
  /**
   * <code>.filesystem.EntryInfo entry = 1 [json_name = "entry"];</code>
   */
  EntryInfoOrBuilder getEntryOrBuilder();
}
